/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Design.RoundedButtonAdmin;
import Design.RoundedButtonAgregar;
import Design.RoundedButtonEditar;
import Design.RoundedButtonEliminar;
import Design.RoundedButtonLugar;
import Design.RoundedPanelAdmin;

/**
 *
 * @author USER
 */
public class Admin_Comentarios extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Comentarios
     */
    public Admin_Comentarios() {
        initComponents();

        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new RoundedButtonLugar("");
        jButton3 = new RoundedButtonLugar("Entrar");
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton4 = new RoundedButtonLugar("Entrar");
        jButton5 = new RoundedButtonLugar("Entrar");
        jButton6 = new RoundedButtonLugar("Entrar");
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        miPanelDiseñado4 = new RoundedPanelAdmin();
        jLabel7 = new javax.swing.JLabel();
        miPanelDiseñado5 = new RoundedPanelAdmin();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton9 = new RoundedButtonEditar("");
        jButton10 =  new RoundedButtonEliminar("");
        jButton15 = new RoundedButtonAgregar("");
        miPanelDiseñado8 = new RoundedPanelAdmin();
        miPanelDiseñado9 = new RoundedPanelAdmin();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        miPanelDiseñado10 = new RoundedPanelAdmin();
        jLabel8 = new javax.swing.JLabel();
        miPanelDiseñado11 = new RoundedPanelAdmin();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton17 = new RoundedButtonEditar("");
        jButton18 =  new RoundedButtonEliminar("");
        miPanelDiseñado12 = new RoundedPanelAdmin();
        jLabel9 = new javax.swing.JLabel();
        miPanelDiseñado13 = new RoundedPanelAdmin();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton11 = new RoundedButtonEditar("");
        jButton12 =  new RoundedButtonEliminar("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1090, 570));

        jPanel1.setBackground(new java.awt.Color(60, 65, 65));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Admin");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 312, 42));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Panel Logo.jpeg"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 80, 70));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Gestión de Lugares.jpeg"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 145, 70, 80));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Usuario(1).jpeg"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 60, 70));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Comentarios.jpeg"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 80, 90));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Comentarios");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 317, -1, -1));

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 180, 50));

        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setText("Lugares");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 180, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Reseñas.jpeg"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 345, 80, 100));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/LogOut(1).jpeg"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 433, 90, 80));

        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 180, 50));

        jButton5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton5.setText("Usuarios");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 180, 50));

        jButton6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton6.setText("Reseñas");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 180, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("COMENTARIOS");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 25, 312, 42));

        miPanelDiseñado4.setBackground(new java.awt.Color(204, 204, 204));
        miPanelDiseñado4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("María Gonzáles.");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        miPanelDiseñado4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        miPanelDiseñado5.setBackground(new java.awt.Color(204, 204, 204));
        miPanelDiseñado5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        miPanelDiseñado4.add(miPanelDiseñado5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nah, el mejor parque que he visitado en la ciudad.");
        miPanelDiseñado4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 400, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("maria@gmail.com");
        miPanelDiseñado4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, -1));

        jButton9.setForeground(new java.awt.Color(0, 0, 0));
        jButton9.setText("Editar Comentario");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        miPanelDiseñado4.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 150, -1));

        jButton10.setText("Eliminar Comentario");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        miPanelDiseñado4.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 34, -1, 20));

        jPanel2.add(miPanelDiseñado4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 740, 110));

        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("+ Agregar Comentario");
        jPanel2.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));

        miPanelDiseñado8.setBackground(new java.awt.Color(204, 204, 204));
        miPanelDiseñado8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        miPanelDiseñado9.setBackground(new java.awt.Color(204, 204, 204));
        miPanelDiseñado9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        miPanelDiseñado8.add(miPanelDiseñado9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Buscar");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        miPanelDiseñado8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Lupa.png"))); // NOI18N
        miPanelDiseñado8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 60, 50));

        jTextField1.setBorder(null);
        miPanelDiseñado8.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 16, 550, -1));

        jPanel2.add(miPanelDiseñado8, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 85, 740, 50));

        miPanelDiseñado10.setBackground(new java.awt.Color(204, 204, 204));
        miPanelDiseñado10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Carlos Rodríguez");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        miPanelDiseñado10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        miPanelDiseñado11.setBackground(new java.awt.Color(204, 204, 204));
        miPanelDiseñado11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        miPanelDiseñado10.add(miPanelDiseñado11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Hermoso lugar para visitar con la familia. Muy recomendado.");
        miPanelDiseñado10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 400, -1));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText("carlos@gmail.com");
        miPanelDiseñado10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, -1));

        jButton17.setForeground(new java.awt.Color(0, 0, 0));
        jButton17.setText("Editar Comentario");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        miPanelDiseñado10.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 150, -1));

        jButton18.setText("Eliminar Comentario");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        miPanelDiseñado10.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 34, -1, 20));

        jPanel2.add(miPanelDiseñado10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 740, 110));

        miPanelDiseñado12.setBackground(new java.awt.Color(204, 204, 204));
        miPanelDiseñado12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("María Gonzáles.");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        miPanelDiseñado12.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        miPanelDiseñado13.setBackground(new java.awt.Color(204, 204, 204));
        miPanelDiseñado13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        miPanelDiseñado12.add(miPanelDiseñado13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("El mirador es genial, pero suele estar muy lleno.");
        miPanelDiseñado12.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 400, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("maria@gmail.com");
        miPanelDiseñado12.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, -1));

        jButton11.setForeground(new java.awt.Color(0, 0, 0));
        jButton11.setText("Editar Comentario");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        miPanelDiseñado12.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 150, -1));

        jButton12.setText("Eliminar Comentario");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        miPanelDiseñado12.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 34, -1, 20));

        jPanel2.add(miPanelDiseñado12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 740, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Admin_Comentarios admin = new Admin_Comentarios();
        admin.setVisible(true);
        this.dispose();     }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Login miLogin = new Login();
        miLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
Admin_Usuarios admin = new Admin_Usuarios();
        admin.setVisible(true);
        this.dispose();     }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
Admin_Reseñas admin = new Admin_Reseñas();
        admin.setVisible(true);
        this.dispose();     }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Comentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Comentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Comentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Comentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Comentarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel miPanelDiseñado10;
    private javax.swing.JPanel miPanelDiseñado11;
    private javax.swing.JPanel miPanelDiseñado12;
    private javax.swing.JPanel miPanelDiseñado13;
    private javax.swing.JPanel miPanelDiseñado4;
    private javax.swing.JPanel miPanelDiseñado5;
    private javax.swing.JPanel miPanelDiseñado8;
    private javax.swing.JPanel miPanelDiseñado9;
    // End of variables declaration//GEN-END:variables
}
