/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Design.RoundedButtonAdmin;
import Design.RoundedButtonAgregar;
import Design.RoundedButtonEditar;
import Design.RoundedButtonEliminar;
import Design.RoundedButtonLugar;
import Design.RoundedPanelAdmin;

/**
 *
 * @author USER
 */
public class Admin_Reseñas extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Reseñas
     */
    public Admin_Reseñas() {
        initComponents();
        
           setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new RoundedButtonLugar("");
        jButton3 = new RoundedButtonLugar("Entrar");
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton4 = new RoundedButtonLugar("Entrar");
        jButton5 = new RoundedButtonLugar("Entrar");
        jButton6 = new RoundedButtonLugar("Entrar");
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        miPanelDiseñado4 = new RoundedPanelAdmin();
        jLabel7 = new javax.swing.JLabel();
        miPanelDiseñado5 = new RoundedPanelAdmin();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton10 =  new RoundedButtonEliminar("");
        jLabel27 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton15 = new RoundedButtonAgregar("");
        miPanelDiseñado10 = new RoundedPanelAdmin();
        jLabel8 = new javax.swing.JLabel();
        miPanelDiseñado11 = new RoundedPanelAdmin();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton18 =  new RoundedButtonEliminar("");
        jLabel19 = new javax.swing.JLabel();
        miPanelDiseñado8 = new RoundedPanelAdmin();
        miPanelDiseñado9 = new RoundedPanelAdmin();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        miPanelDiseñado12 = new RoundedPanelAdmin();
        jLabel9 = new javax.swing.JLabel();
        miPanelDiseñado13 = new RoundedPanelAdmin();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton12 =  new RoundedButtonEliminar("");
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        miPanelDiseñado14 = new RoundedPanelAdmin();
        miPanelDiseñado15 = new RoundedPanelAdmin();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(60, 65, 65));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Admin");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 312, 42));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Panel Logo.jpeg"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 80, 70));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Gestión de Lugares.jpeg"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 145, 70, 80));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Usuario(1).jpeg"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 60, 70));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Comentarios.jpeg"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 80, 90));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Comentarios");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 317, -1, -1));

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 180, 50));

        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setText("Lugares");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 180, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Reseñas.jpeg"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 345, 80, 100));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/LogOut(1).jpeg"))); // NOI18N
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 433, 90, 80));

        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 180, 50));

        jButton5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton5.setText("Usuarios");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 180, 50));

        jButton6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton6.setText("Reseñas");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 180, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("RESEÑAS");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 25, 312, 42));

        miPanelDiseñado4.setBackground(new java.awt.Color(204, 204, 204));
        miPanelDiseñado4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("María Gonzáles.");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        miPanelDiseñado4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        miPanelDiseñado5.setBackground(new java.awt.Color(204, 204, 204));
        miPanelDiseñado5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        miPanelDiseñado4.add(miPanelDiseñado5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Lugar muy limpio y seguro.");
        miPanelDiseñado4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 190, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("maria@gmail.com");
        miPanelDiseñado4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, -1));

        jButton10.setText("Eliminar Reseña");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        miPanelDiseñado4.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, 20));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/1707847293119892-0__1_-removebg-preview.png"))); // NOI18N
        miPanelDiseñado4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 230, 50));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/gratis-png-me-gusta__1_-removebg-preview.png"))); // NOI18N
        miPanelDiseñado4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 60, 50));

        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("Me gusta : 0");
        miPanelDiseñado4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/R__2___1_-removebg-preview.png"))); // NOI18N
        miPanelDiseñado4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 60, 50));

        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("No me gusta : 0");
        miPanelDiseñado4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        jPanel3.add(miPanelDiseñado4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 740, 110));

        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("+ Agregar Reseña");
        jPanel3.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));

        miPanelDiseñado10.setBackground(new java.awt.Color(204, 204, 204));
        miPanelDiseñado10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jonnathan Guzmán.");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        miPanelDiseñado10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        miPanelDiseñado11.setBackground(new java.awt.Color(204, 204, 204));
        miPanelDiseñado11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        miPanelDiseñado10.add(miPanelDiseñado11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Más aseo y dar mantenimiento");
        miPanelDiseñado10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 210, -1));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText("Abril 4, 2024.");
        miPanelDiseñado10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, -1));

        jButton18.setText("Eliminar Reseña");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        miPanelDiseñado10.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, 20));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/unnamed__1_-removebg-preview.png"))); // NOI18N
        miPanelDiseñado10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 230, 50));

        miPanelDiseñado8.setBackground(new java.awt.Color(204, 204, 204));
        miPanelDiseñado8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        miPanelDiseñado9.setBackground(new java.awt.Color(204, 204, 204));
        miPanelDiseñado9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        miPanelDiseñado8.add(miPanelDiseñado9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/gratis-png-me-gusta__1_-removebg-preview.png"))); // NOI18N
        miPanelDiseñado8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Me gusta : 2");
        miPanelDiseñado8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        miPanelDiseñado10.add(miPanelDiseñado8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 140, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/gratis-png-me-gusta__1_-removebg-preview.png"))); // NOI18N
        miPanelDiseñado10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 60, 50));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/R__2___1_-removebg-preview.png"))); // NOI18N
        miPanelDiseñado10.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 60, 50));

        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setText("No me gusta : 0");
        miPanelDiseñado10.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        jPanel3.add(miPanelDiseñado10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 740, 110));

        miPanelDiseñado12.setBackground(new java.awt.Color(204, 204, 204));
        miPanelDiseñado12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("María Gonzáles.");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        miPanelDiseñado12.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        miPanelDiseñado13.setBackground(new java.awt.Color(204, 204, 204));
        miPanelDiseñado13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        miPanelDiseñado12.add(miPanelDiseñado13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("NO incluye la entrada. Decepción.");
        miPanelDiseñado12.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 230, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Mayo 5, 2025");
        miPanelDiseñado12.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, -1));

        jButton12.setText("Eliminar Reseña");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        miPanelDiseñado12.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, 20));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/unnamed__2___1_-removebg-preview.png"))); // NOI18N
        miPanelDiseñado12.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 230, 50));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/gratis-png-me-gusta__1_-removebg-preview.png"))); // NOI18N
        miPanelDiseñado12.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 60, 50));

        jLabel34.setForeground(new java.awt.Color(51, 51, 51));
        jLabel34.setText("Me gusta : 0");
        miPanelDiseñado12.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/R__2___1_-removebg-preview.png"))); // NOI18N
        miPanelDiseñado12.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 60, 50));

        jLabel36.setForeground(new java.awt.Color(51, 51, 51));
        jLabel36.setText("No me gusta : 0");
        miPanelDiseñado12.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        jPanel3.add(miPanelDiseñado12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 740, 110));

        miPanelDiseñado14.setBackground(new java.awt.Color(204, 204, 204));
        miPanelDiseñado14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        miPanelDiseñado15.setBackground(new java.awt.Color(204, 204, 204));
        miPanelDiseñado15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        miPanelDiseñado14.add(miPanelDiseñado15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel22.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Buscar");
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        miPanelDiseñado14.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Lupa.png"))); // NOI18N
        miPanelDiseñado14.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 60, 50));

        jTextField2.setBorder(null);
        miPanelDiseñado14.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 16, 550, -1));

        jPanel3.add(miPanelDiseñado14, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 85, 740, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 Admin_Comentarios miPanel = new Admin_Comentarios();
        miPanel.setVisible(true);
        this.dispose();    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Admin_Lugares miPanel = new Admin_Lugares();
        miPanel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Login miLogin = new Login();
        miLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 Admin_Usuarios miUsuario = new Admin_Usuarios();
        miUsuario.setVisible(true);
        this.dispose();    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
 Admin_Reseñas miUsuario = new Admin_Reseñas();
        miUsuario.setVisible(true);
        this.dispose();    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Reseñas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Reseñas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Reseñas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Reseñas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Reseñas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel miPanelDiseñado10;
    private javax.swing.JPanel miPanelDiseñado11;
    private javax.swing.JPanel miPanelDiseñado12;
    private javax.swing.JPanel miPanelDiseñado13;
    private javax.swing.JPanel miPanelDiseñado14;
    private javax.swing.JPanel miPanelDiseñado15;
    private javax.swing.JPanel miPanelDiseñado4;
    private javax.swing.JPanel miPanelDiseñado5;
    private javax.swing.JPanel miPanelDiseñado8;
    private javax.swing.JPanel miPanelDiseñado9;
    // End of variables declaration//GEN-END:variables
}
