/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Animations.Animator1;
import Design.ComboBox.Combobox;
import Design.RoundedButtonActualizar;
import Design.RoundedButtonAdmin;
import Design.RoundedButtonLugar;
import Design.RoundedPanelAdmin;
import Design.RoundedButtonEditar;
import Design.RoundedButtonEliminar;
import Design.RoundedButtonAgregar;
import Design.RoundedButtonEliminarRe;
import Design.RoundedButtonInsertar;
import Design.RoundedButtonSalirRe;
import Design.RoundedPannelGris;
import Design.Tabla.EncabezadoModernoRenderer;
import Design.Tabla.EstiloTablaModerna;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URL;
import javax.swing.BorderFactory;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.TableCellRenderer;
import raven.glasspanepopup.GlassPanePopup;

/**
 *
 * @author USER
 */
public class Admin_Lugares extends javax.swing.JFrame {

    //Permitir entrar a la ventana:
    private boolean sinBordes = true;
    
    
    private String Busqueda = "Buscar Lugar....";

    /**
     * Creates new form Admin_Lugares
     */
    public Admin_Lugares(boolean sinBordes) {
        if (sinBordes) {
            setUndecorated(true);
        }

        initComponents();

        personalizarTabla(jTable1);

        //Para quitar la selección de la tabla:
        this.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                jTable1.clearSelection();
            }
        });

        //Instanciar el Popup:
        GlassPanePopup.install(this);

        //Darle ScrollPanel:
        jScrollPane1.setBorder(BorderFactory.createLineBorder(new Color(220, 220, 220)));

        //Extender la ventana al máximo: 
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        // Para pantalla completa:
        setExtendedState(Ventana_Principal.MAXIMIZED_BOTH);

        setLocationRelativeTo(null);

        //Método Placeholder:
        ponerPlaceholder(Busqueda2, Busqueda);

        //Quitar el fondo al TextField:
        Busqueda2.setOpaque(false);
        Busqueda2.setBorder(null);
        Busqueda2.setForeground(Color.BLACK);

        //Fuentes:
        Lugares.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 35));
        Busqueda2.setFont(new Font("Segoe UI Light", Font.PLAIN, 14));
        Tipo.setFont(new Font("Segoe UI Light", Font.PLAIN, 14));
        Calificacion.setFont(new Font("Segoe UI Light", Font.PLAIN, 14));

    }

    //Personalizar la tabla:
    public void personalizarTabla(JTable tabla) {

        tabla.setRowHeight(32);
        tabla.setShowVerticalLines(false);
        tabla.setShowHorizontalLines(false);
        tabla.setGridColor(new Color(220, 220, 220));
        tabla.setFont(new Font("Segoe UI Light", Font.PLAIN, 14));

        tabla.getTableHeader().setDefaultRenderer(new EncabezadoModernoRenderer());
        tabla.getTableHeader().setReorderingAllowed(false);

        TableCellRenderer rendererFilas = new EstiloTablaModerna();
        for (int i = 0; i < tabla.getColumnCount(); i++) {
            tabla.getColumnModel().getColumn(i).setCellRenderer(rendererFilas);
        }

        tabla.setIntercellSpacing(new Dimension(0, 0));
        tabla.setFillsViewportHeight(true);
        tabla.setBackground(new Color(250, 250, 250));
    }

    private void ponerPlaceholder(JTextField campo, String textoPorDefecto) {
        campo.setText(textoPorDefecto);
        campo.setForeground(Color.GRAY);

        campo.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (campo.getText().equals(textoPorDefecto)) {
                    campo.setText("");
                    campo.setForeground(new Color(0, 0, 0, 255));
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (campo.getText().isEmpty()) {
                    campo.setForeground(Color.GRAY);
                    campo.setText(textoPorDefecto);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Lugares = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new RoundedPannelGris();
        Busqueda2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Tipo = new Combobox<>(new String[]{
        });
        Calificacion = new Combobox<>(new String[]{
        });
        jLabel1 = new javax.swing.JLabel();
        Insertar = new RoundedButtonInsertar("");
        jLabel2 = new javax.swing.JLabel();
        Eliminar = new RoundedButtonEliminarRe("");
        jLabel3 = new javax.swing.JLabel();
        Actualizar = new RoundedButtonActualizar("");
        jLabel5 = new javax.swing.JLabel();
        Salir = new RoundedButtonSalirRe("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1390, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 247, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Lugares 2.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, 70));

        Lugares.setForeground(new java.awt.Color(255, 255, 255));
        Lugares.setText("Lugares de Interés");
        jPanel2.add(Lugares, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 120));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 1330, 400));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Busqueda2.setForeground(new java.awt.Color(255, 255, 255));
        Busqueda2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Busqueda2.setOpaque(true);
        Busqueda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Busqueda2ActionPerformed(evt);
            }
        });
        jPanel4.add(Busqueda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 420, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Lupa__Ícono_-removebg-preview (1).png"))); // NOI18N
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, -24, 48, 80));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, 30));

        Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo", "Museos", "Iglesias", "Cafeterías", "Hoteles", "Parques" }));
        jPanel1.add(Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 270, 30));

        Calificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Calificación", "5 estrellas", "4 estrellas", "3 estrellas", "2 estrellas", "1 estrella" }));
        jPanel1.add(Calificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 150, 270, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/gestion-del-tiempo (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 660, 60, 60));

        Insertar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Insertar.setText("Insertar");
        Insertar.setBorderPainted(false);
        Insertar.setContentAreaFilled(false);
        Insertar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Insertar.setFocusPainted(false);
        Insertar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarActionPerformed(evt);
            }
        });
        jPanel1.add(Insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 670, 160, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/borrar (3) (1).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 660, 50, 60));

        Eliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.setBorderPainted(false);
        Eliminar.setContentAreaFilled(false);
        Eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Eliminar.setFocusPainted(false);
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 670, 160, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/actualizar (2) (1).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 670, 70, 50));

        Actualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Actualizar.setText("Actualizar");
        Actualizar.setBorderPainted(false);
        Actualizar.setContentAreaFilled(false);
        Actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Actualizar.setFocusPainted(false);
        Actualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 670, 160, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/cerrar-sesion (1).png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 660, 50, 60));

        Salir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Salir.setText("Salir");
        Salir.setBorderPainted(false);
        Salir.setContentAreaFilled(false);
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.setFocusPainted(false);
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 670, 160, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Busqueda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Busqueda2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Busqueda2ActionPerformed

    private void InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarActionPerformed
        Ventana_Insertar_Lugar ayudaPanel = new Ventana_Insertar_Lugar();

        GlassPanePopup.showPopup(ayudaPanel);


    }//GEN-LAST:event_InsertarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed

    }//GEN-LAST:event_EliminarActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed


    }//GEN-LAST:event_ActualizarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed


    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    //Para entrar desde aquí:
    public static void main(String[] args) {
        URL url = Admin_Lugares.class.getResource("/Imágenes/Panel Logo.jpeg");
        System.out.println("URL encontrada: " + url);

        // Verificamos si el sistema soporta translucidez
        GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        boolean soportaTransparencia = gd.isWindowTranslucencySupported(GraphicsDevice.WindowTranslucency.TRANSLUCENT);

        // Creamos la ventana
        Admin_Lugares ventana = new Admin_Lugares(true); // true = sin bordes

        // Si el sistema lo permite, iniciamos con opacidad 0
        if (soportaTransparencia) {
            ventana.setOpacity(0f);
        }

        // Mostramos la ventana con animación
        ventana.setVisible(true);

        if (soportaTransparencia) {
            Animations.Animator1.fadeIn(ventana);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JTextField Busqueda2;
    private javax.swing.JComboBox<String> Calificacion;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Insertar;
    private javax.swing.JLabel Lugares;
    private javax.swing.JButton Salir;
    private javax.swing.JComboBox<String> Tipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
