/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;
import Design.RoundedPanel;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import javax.swing.BorderFactory;
import raven.glasspanepopup.GlassPanePopup;
import Design.RoundedButtonEntendido;
/**
 *
 * @author USER
 */
public class AyudaMensaje extends javax.swing.JPanel {

    /**
     * Creates new form AyudaMensaje
     */
    public AyudaMensaje() {
        setOpaque(false);

        initComponents();

        Recomendaciones.setFont(new Font("CocogooseProTrial", Font.PLAIN, 18));
        NombreUsuario.setFont(new Font("Caviar Dreams", Font.PLAIN, 15));
        Nombres.setFont(new Font("CocogooseProTrial", Font.PLAIN, 11));
        Nombre.setFont(new Font("Caviar Dreams", Font.PLAIN, 13));
        Contraseña.setFont(new Font("Caviar Dreams", Font.PLAIN, 15));
        Caracteres.setFont(new Font("CocogooseProTrial", Font.PLAIN, 11));
        Signos.setFont(new Font("CocogooseProTrial", Font.PLAIN, 11));
        SignosRaros.setFont(new Font("CocogooseProTrial", Font.PLAIN, 11));
        ava.setFont(new Font("Caviar Dreams", Font.PLAIN, 13));
        Correo.setFont(new Font("Caviar Dreams", Font.PLAIN, 15));
        Lab1.setFont(new Font("CocogooseProTrial", Font.PLAIN, 11));
        Lab2.setFont(new Font("CocogooseProTrial", Font.PLAIN, 11));
        Lab3.setFont(new Font("CocogooseProTrial", Font.PLAIN, 11));
        Lab4.setFont(new Font("CocogooseProTrial", Font.PLAIN, 11));
        Lab5.setFont(new Font("Caviar Dreams", Font.PLAIN, 13));
        Entendido.setFont(new Font("Caviar Dreams Bold", Font.PLAIN, 15));

    }

    //Para darle esos bordes:
    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 25, 25));
        g2.dispose();
        super.paintComponent(grphcs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Recomendaciones = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NombreUsuario = new javax.swing.JLabel();
        Nombres = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Contraseña = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Caracteres = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Signos = new javax.swing.JLabel();
        SignosRaros = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ava = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Correo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Lab1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Lab2 = new javax.swing.JLabel();
        Lab3 = new javax.swing.JLabel();
        Lab4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Lab5 = new javax.swing.JLabel();
        Entendido = new RoundedButtonEntendido("");

        setPreferredSize(new java.awt.Dimension(800, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Recomendaciones.setForeground(new java.awt.Color(150, 125, 116));
        Recomendaciones.setText("RECOMENDACIONES PARA CREAR TU CUENTA");
        add(Recomendaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/settings (3).png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 6, 60, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/boy (2).png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 110, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/check (2) (1).png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 70, 70));

        NombreUsuario.setForeground(new java.awt.Color(237, 79, 31));
        NombreUsuario.setText("Nombre de Usuario");
        add(NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        Nombres.setText("Evita espacios, tíldes o números.");
        add(Nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 200, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/accept (2) (1).png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, -1, 40));

        Nombre.setText("Sebastian.");
        add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 230, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/secure (1).png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 90, 90));

        Contraseña.setForeground(new java.awt.Color(237, 79, 31));
        Contraseña.setText("Contraseña");
        add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/check (2) (1).png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 70, 70));

        Caracteres.setText("Mínimo ocho caracteres,");
        add(Caracteres, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/check (2) (1).png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 70, 70));

        Signos.setText("Incluye  letras, números y signos");
        add(Signos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        SignosRaros.setText("(#$&.).");
        add(SignosRaros, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/accept (2) (1).png"))); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 40));

        ava.setText("avasuca2024$.");
        add(ava, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 272, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/communication (1).png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 100, 90));

        Correo.setForeground(new java.awt.Color(237, 79, 31));
        Correo.setText("Correo");
        add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/check (2) (1).png"))); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 70, 70));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/check (2) (1).png"))); // NOI18N
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 70, 70));

        Lab1.setText("Aségurate de usar @.");
        add(Lab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/check (2) (1).png"))); // NOI18N
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 70, 70));

        Lab2.setText("Usa letras, números, signos.");
        add(Lab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, -1, -1));

        Lab3.setText("(. _)");
        add(Lab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, -1, -1));

        Lab4.setText("No olvides el dominio.");
        add(Lab4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/check (2) (1).png"))); // NOI18N
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 70, 70));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/accept (2) (1).png"))); // NOI18N
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, 40));

        Lab5.setText("example22@gmail.com");
        add(Lab5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, -1, -1));

        Entendido.setText("Entendido");
        Entendido.setBorderPainted(false);
        Entendido.setContentAreaFilled(false);
        Entendido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Entendido.setFocusPainted(false);
        Entendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntendidoActionPerformed(evt);
            }
        });
        add(Entendido, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 220, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void EntendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntendidoActionPerformed
GlassPanePopup.closePopupLast();    }//GEN-LAST:event_EntendidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Caracteres;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JLabel Correo;
    private javax.swing.JButton Entendido;
    private javax.swing.JLabel Lab1;
    private javax.swing.JLabel Lab2;
    private javax.swing.JLabel Lab3;
    private javax.swing.JLabel Lab4;
    private javax.swing.JLabel Lab5;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel NombreUsuario;
    private javax.swing.JLabel Nombres;
    private javax.swing.JLabel Recomendaciones;
    private javax.swing.JLabel Signos;
    private javax.swing.JLabel SignosRaros;
    private javax.swing.JLabel ava;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
