/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ControladorIglesia;
import Design.RoundedButtonInsertar;
import Design.RoundedPanelLugares;
import Modelo.IglesiaDetalleVista;
import Modelo.IglesiaVista;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.time.LocalTime;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class PanelCardIglesia extends javax.swing.JPanel {

    private IglesiaVista vista;
    
    /**
     * Creates new form PanelCardIglesia
     */
    public PanelCardIglesia(IglesiaVista vista) {
        initComponents();
        this.vista = vista;

        //Fuentes:
        lblNombre.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 20));

        lblHoraApertura.setFont(new Font("Segoe UI Light", Font.PLAIN, 12));
        lblHoraCierre.setFont(new Font("Segoe UI Light", Font.PLAIN, 12));

    }

    public PanelCardIglesia(int id, String nombre, String horaApertura, String horaCierre, byte[] imagenBytes) {
        initComponents();
        System.out.println(id);
        LocalTime apertura = null;
        LocalTime cierre = null;
        try {
            if (horaApertura != null && !horaApertura.isEmpty()) {
                apertura = LocalTime.parse(horaApertura);
            }
            if (horaCierre != null && !horaCierre.isEmpty()) {
                cierre = LocalTime.parse(horaCierre);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        this.vista = new IglesiaVista(id, nombre, apertura, cierre, imagenBytes);
        lblNombre.setText(nombre);
        lblHoraApertura.setText("Entrada: " + horaApertura);
        lblHoraCierre.setText("Salida: " + horaCierre);

        lblNombre.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 20));
        lblHoraApertura.setFont(new Font("Segoe UI Light", Font.PLAIN, 12));
        lblHoraCierre.setFont(new Font("Segoe UI Light", Font.PLAIN, 12));

        if (imagenBytes != null) {
            ImageIcon icono = new ImageIcon(imagenBytes);
            Image img = icono.getImage().getScaledInstance(350, 180, Image.SCALE_SMOOTH);
            lblImagen.setIcon(new ImageIcon(img));
        }

        btnVer.addActionListener(e -> mostrarVentanaDetalle());
    }

    @Override
    public Dimension getPreferredSize() {
        return new Dimension(350, 340);
    }

    private void mostrarVentanaDetalle() {
        try {
            int id = vista.getId();
            ControladorIglesia ctrl = new ControladorIglesia();
            IglesiaDetalleVista detalle = ctrl.obtenerDetalleIglesia(id);

            if (detalle != null) {
                Ventana_VerIglesias ventana = new Ventana_VerIglesias(detalle);
                ventana.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No se encontraron los datos completos.");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Error al mostrar la iglesia:\n" + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new RoundedPanelLugares();
        lblImagenIglesia = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        lblReloj = new javax.swing.JLabel();
        lblHoraCierre = new javax.swing.JLabel();
        lblHoraApertura = new javax.swing.JLabel();
        btnVer = new RoundedButtonInsertar("");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagenIglesia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Iglesias 3.png"))); // NOI18N
        jPanel1.add(lblImagenIglesia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 70, 90));

        lblNombre.setForeground(new java.awt.Color(49, 49, 49));
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 240, 30));
        jPanel1.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 180));

        lblReloj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/oRA.png"))); // NOI18N
        jPanel1.add(lblReloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 240, 30, 30));

        lblHoraCierre.setForeground(new java.awt.Color(127, 140, 141));
        jPanel1.add(lblHoraCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 80, 20));

        lblHoraApertura.setForeground(new java.awt.Color(127, 140, 141));
        jPanel1.add(lblHoraApertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 242, 80, 20));

        btnVer.setText("Ver");
        btnVer.setBorderPainted(false);
        btnVer.setContentAreaFilled(false);
        btnVer.setFocusPainted(false);
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        jPanel1.add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 90, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 340));
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHoraApertura;
    private javax.swing.JLabel lblHoraCierre;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblImagenIglesia;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblReloj;
    // End of variables declaration//GEN-END:variables
}
