/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Design.RoundedButtonIglesias;
import Design.RoundedButtonMiradores;
import Design.RoundedButtonMuseos;
import Design.RoundedPannelGris;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import Design.RoundedButtonParques;
import Design.RoundedButtonRanking;
/**
 *
 * @author USER
 */
public class Ventanas_MostrarMás extends javax.swing.JPanel {

    private final String BusquedaText = "Buscar Iglesias, Parques, Museos, Miradores";

    /**
     * Creates new form Ventanas_MostrarMás
     */
    public Ventanas_MostrarMás() {
        initComponents();

        //Fuentes:
        Busqueda2.setFont(new Font("Caviar Dreams", Font.PLAIN, 17));
        Categoría.setFont(new Font("CocogooseProTrial", Font.PLAIN, 17));
        Parques.setFont(new Font("Caviar Dreams", Font.PLAIN, 14));
        IglesiasBoton.setFont(new Font("Caviar Dreams", Font.PLAIN, 14));
        Miradores1.setFont(new Font("Caviar Dreams", Font.PLAIN, 14));
        Museos.setFont(new Font("Caviar Dreams", Font.PLAIN, 14));
        Ranking2.setFont(new Font("Caviar Dreams", Font.PLAIN, 14));
        Catedral.setFont(new Font("Caviar Dreams", Font.PLAIN, 14));

        //Hacer invisible el JTextField de Búsqueda:
        Busqueda2.setOpaque(false);
        Busqueda2.setBorder(null);
        Busqueda2.setForeground(Color.BLACK);

        //Hacer el Holder para la búsqueda:
        ponerPlaceholder(Busqueda2, BusquedaText);

    }

    private void ponerPlaceholder(JTextField campo, String textoPorDefecto) {
        campo.setText(textoPorDefecto);
        campo.setForeground(Color.GRAY);

        campo.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (campo.getText().equals(textoPorDefecto)) {
                    campo.setText("");
                    campo.setForeground(new Color(160, 160, 160));
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (campo.getText().isEmpty()) {
                    campo.setForeground(Color.GRAY);
                    campo.setText(textoPorDefecto);
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new RoundedPannelGris();
        Busqueda2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Categoría = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Parques = new RoundedButtonParques("");
        jLabel17 = new javax.swing.JLabel();
        IglesiasBoton = new RoundedButtonIglesias("");
        jLabel1 = new javax.swing.JLabel();
        Miradores1 = new javax.swing.JLabel();
        Miradores =  new RoundedButtonMiradores("");
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Museos = new RoundedButtonMuseos("");
        Ranking2 = new javax.swing.JLabel();
        Ranking =  new RoundedButtonRanking("");
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Catedral = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1140, 830));
        setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(242, 242, 242));
        jPanel1.setPreferredSize(new java.awt.Dimension(1140, 830));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Salir (2) (2).png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 12, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(Busqueda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 480, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Lupa__Ícono_-removebg-preview (1).png"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -14, 48, 80));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 560, 50));

        Categoría.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        Categoría.setForeground(new java.awt.Color(237, 79, 31));
        Categoría.setText("Filtar por Categoría:");
        jPanel1.add(Categoría, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/hombre-caminando (2).png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 106, -1, -1));

        Parques.setText("Parques");
        Parques.setContentAreaFilled(false);
        Parques.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(Parques, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 96, 130, 40));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/iglesia (2).png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 106, -1, -1));

        IglesiasBoton.setText("Iglesias");
        IglesiasBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(IglesiasBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 96, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/binoculares (2).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 96, 40, 40));

        Miradores1.setForeground(new java.awt.Color(255, 255, 255));
        Miradores1.setText("Miradores");
        jPanel1.add(Miradores1, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 108, -1, -1));

        Miradores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(Miradores, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 96, 130, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/museo-britanico (2).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 96, 40, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/4-estrellas (2).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 86, 70, 60));

        Museos.setText("Museos");
        Museos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(Museos, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 96, 130, 40));

        Ranking2.setForeground(new java.awt.Color(255, 255, 255));
        Ranking2.setText("Mejor Ranking");
        jPanel1.add(Ranking2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 106, -1, -1));
        jPanel1.add(Ranking, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 96, 150, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/circulo (1).png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 728, 40, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/circulo (1).png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 728, 40, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/circulo (1).png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 728, 40, 40));

        Catedral.setForeground(new java.awt.Color(0, 0, 0));
        Catedral.setText("Página Uno");
        jPanel1.add(Catedral, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 738, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1128, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir?", "Exit", dialog);
        if (result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel5MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Busqueda2;
    private javax.swing.JLabel Catedral;
    private javax.swing.JLabel Categoría;
    private javax.swing.JButton IglesiasBoton;
    private javax.swing.JButton Miradores;
    private javax.swing.JLabel Miradores1;
    private javax.swing.JButton Museos;
    private javax.swing.JButton Parques;
    private javax.swing.JButton Ranking;
    private javax.swing.JLabel Ranking2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
