/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Design.RoundedButtonInsertar;
import Design.RoundedButtonLugaresEvent;
import Design.RoundedButtonNegocios;
import Design.RoundedButtonSalirRe;
import Design.RoundedPanelAdmin;
import Design.RoundedPanelBordesResenas;
import Design.RoundedPanelHoteles;
import Design.RoundedPanelResenas;
import Design.RoundedPannelGris;
import java.awt.Font;

/**
 *
 * @author USER
 */
public class Ventana_Resenas extends javax.swing.JFrame {

    //Permitir entrar a la ventana:
    private boolean sinBordes = true;

    /**
     * Creates new form Ventana_Resenas
     */
    public Ventana_Resenas(boolean sinBordes) {

        if (sinBordes) {
            setUndecorated(true);
        }

        initComponents();

        //Fuentes:
        Huellas.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 20));
        Cuencanas.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 20));
        Conteo_User.setFont(new Font("Segoe UI Semibold", Font.BOLD, 35));
        Gestion.setFont(new Font("Segoe UI Light", Font.PLAIN, 20));
        Conteo_User1.setFont(new Font("Segoe UI Semibold", Font.BOLD, 35));
        Gestion1.setFont(new Font("Segoe UI Light", Font.PLAIN, 20));
        Conteo_User2.setFont(new Font("Segoe UI Semibold", Font.BOLD, 35));
        Gestion2.setFont(new Font("Segoe UI Light", Font.PLAIN, 20));
        Conteo_User3.setFont(new Font("Segoe UI Semibold", Font.BOLD, 35));
        Gestion3.setFont(new Font("Segoe UI Light", Font.PLAIN, 20));
        Comercial.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 20));
        AAA.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 20));
        Gestionar.setFont(new Font("Segoe UI Light", Font.PLAIN, 15));
        Ges.setFont(new Font("Segoe UI Light", Font.PLAIN, 14));
        Gestion4.setFont(new Font("Segoe UI Light", Font.PLAIN, 15));
        Conteo_User4.setFont(new Font("Segoe UI Semibold", Font.BOLD, 25));
        Museos.setFont(new Font("Segoe UI Light", Font.PLAIN, 15));
        Gestion6.setFont(new Font("Segoe UI Light", Font.PLAIN, 15));
        Gestion7.setFont(new Font("Segoe UI Light", Font.PLAIN, 15));
        Conteo_User7.setFont(new Font("Segoe UI Semibold", Font.BOLD, 25));
        Muse5.setFont(new Font("Segoe UI Semibold", Font.BOLD, 35));
        Conteo_User6.setFont(new Font("Segoe UI Semibold", Font.BOLD, 35));
        Conteo_User7.setFont(new Font("Segoe UI Semibold", Font.BOLD, 35));
        Gestion8.setFont(new Font("Segoe UI Light", Font.PLAIN, 15));
        Conteo_User8.setFont(new Font("Segoe UI Semibold", Font.BOLD, 35));
        Gestion9.setFont(new Font("Segoe UI Light", Font.PLAIN, 15));
        Conteo_User9.setFont(new Font("Segoe UI Semibold", Font.BOLD, 35));
        Mis.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 20));

        //Extender la ventana al máximo: 
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        // Para pantalla completa:
        setExtendedState(Ventana_Principal.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new RoundedPanelAdmin();
        jPanel4 = new RoundedPanelResenas();
        Conteo_User = new javax.swing.JLabel();
        Gestion = new javax.swing.JLabel();
        jPanel5 = new RoundedPanelResenas();
        Gestion1 = new javax.swing.JLabel();
        Conteo_User4 = new javax.swing.JLabel();
        jPanel6 = new RoundedPanelResenas();
        Conteo_User2 = new javax.swing.JLabel();
        Gestion2 = new javax.swing.JLabel();
        jPanel7 = new RoundedPanelResenas();
        Conteo_User3 = new javax.swing.JLabel();
        Gestion3 = new javax.swing.JLabel();
        Comercial = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        Huellas = new javax.swing.JLabel();
        Cuencanas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel8 = new RoundedPanelAdmin();
        jPanel9 = new RoundedPanelAdmin();
        jPanel10 = new RoundedPanelAdmin();
        jPanel11 = new RoundedPanelHoteles();
        jLabel3 = new javax.swing.JLabel();
        AAA = new javax.swing.JLabel();
        jPanel12 = new RoundedPanelBordesResenas();
        Gestion4 = new javax.swing.JLabel();
        Conteo_User1 = new javax.swing.JLabel();
        jPanel16 = new RoundedPanelBordesResenas();
        Gestion6 = new javax.swing.JLabel();
        Conteo_User6 = new javax.swing.JLabel();
        jPanel13 = new RoundedPanelBordesResenas();
        Museos = new javax.swing.JLabel();
        Muse5 = new javax.swing.JLabel();
        jPanel17 = new RoundedPanelBordesResenas();
        Gestion7 = new javax.swing.JLabel();
        Conteo_User7 = new javax.swing.JLabel();
        jPanel14 = new RoundedPanelBordesResenas();
        Gestion8 = new javax.swing.JLabel();
        Conteo_User8 = new javax.swing.JLabel();
        jPanel15 = new RoundedPanelBordesResenas();
        Gestion9 = new javax.swing.JLabel();
        Conteo_User9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Ges = new javax.swing.JLabel();
        Gestionar = new RoundedButtonLugaresEvent("");
        jPanel18 = new RoundedButtonNegocios();
        jLabel5 = new javax.swing.JLabel();
        Comercial1 = new javax.swing.JLabel();
        Mis = new javax.swing.JLabel();
        jButton1 = new RoundedButtonInsertar("");
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new RoundedButtonSalirRe("");
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(248, 250, 252));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Conteo_User.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        Conteo_User.setForeground(new java.awt.Color(105, 120, 200));
        Conteo_User.setText("0");
        jPanel4.add(Conteo_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 50, 30));

        Gestion.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Gestion.setForeground(new java.awt.Color(127, 140, 141));
        Gestion.setText("Reseñas Totales");
        jPanel4.add(Gestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 140, 20));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 250, 110));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Gestion1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Gestion1.setForeground(new java.awt.Color(127, 140, 141));
        Gestion1.setText("Calificación Promedio");
        jPanel5.add(Gestion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 210, 20));

        Conteo_User4.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        Conteo_User4.setForeground(new java.awt.Color(105, 120, 200));
        Conteo_User4.setText("0");
        jPanel5.add(Conteo_User4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 50, 30));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 250, 110));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Conteo_User2.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        Conteo_User2.setForeground(new java.awt.Color(105, 120, 200));
        Conteo_User2.setText("0");
        jPanel6.add(Conteo_User2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 50, 30));

        Gestion2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Gestion2.setForeground(new java.awt.Color(127, 140, 141));
        Gestion2.setText("Reseñas este mes");
        jPanel6.add(Gestion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 170, 20));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 250, 110));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Conteo_User3.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        Conteo_User3.setForeground(new java.awt.Color(105, 120, 200));
        Conteo_User3.setText("0");
        jPanel7.add(Conteo_User3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 50, 30));

        Gestion3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Gestion3.setForeground(new java.awt.Color(127, 140, 141));
        Gestion3.setText("Reseñas Positivas");
        jPanel7.add(Gestion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 170, 20));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 250, 110));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 1220, 150));

        Comercial.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Comercial.setForeground(new java.awt.Color(44, 62, 80));
        Comercial.setText("Análisis de Reseñas");
        jPanel1.add(Comercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        jPanel2.setBackground(new java.awt.Color(126, 83, 181));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Copilot_20250610_114322 (3).png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 60, 70));

        Huellas.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Huellas.setForeground(new java.awt.Color(255, 255, 255));
        Huellas.setText("Huellas ");
        jPanel2.add(Huellas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 26, -1, -1));

        Cuencanas.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Cuencanas.setForeground(new java.awt.Color(255, 255, 255));
        Cuencanas.setText("Cuencanas");
        jPanel2.add(Cuencanas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 44, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Comentario.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 0, 80, 90));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Rueda.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 232, 110, 80));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 1220, 20));

        jPanel8.add(jPanel9);

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 330, 240));
        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 330, 240));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Resenas Icon.png"))); // NOI18N
        jPanel11.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 70, 60));

        AAA.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        AAA.setForeground(new java.awt.Color(44, 62, 80));
        AAA.setText("Resumen por Tipo");
        jPanel11.add(AAA, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Gestion4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Gestion4.setForeground(new java.awt.Color(127, 140, 141));
        Gestion4.setText("Parques");
        jPanel12.add(Gestion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 12, 110, 20));

        Conteo_User1.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        Conteo_User1.setForeground(new java.awt.Color(155, 89, 182));
        Conteo_User1.setText("0");
        jPanel12.add(Conteo_User1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 50, 30));

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 200, 90));

        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Gestion6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Gestion6.setForeground(new java.awt.Color(127, 140, 141));
        Gestion6.setText("Restaurantes");
        jPanel16.add(Gestion6, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 10, 110, 20));

        Conteo_User6.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        Conteo_User6.setForeground(new java.awt.Color(155, 89, 182));
        Conteo_User6.setText("0");
        jPanel16.add(Conteo_User6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 50, 30));

        jPanel11.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 200, 90));

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Museos.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Museos.setForeground(new java.awt.Color(127, 140, 141));
        Museos.setText("Museos");
        jPanel13.add(Museos, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 12, 110, 20));

        Muse5.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        Muse5.setForeground(new java.awt.Color(155, 89, 182));
        Muse5.setText("0");
        jPanel13.add(Muse5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 50, 30));

        jPanel11.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 200, 90));

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Gestion7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Gestion7.setForeground(new java.awt.Color(127, 140, 141));
        Gestion7.setText("Iglesias");
        jPanel17.add(Gestion7, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 10, 110, 20));

        Conteo_User7.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        Conteo_User7.setForeground(new java.awt.Color(155, 89, 182));
        Conteo_User7.setText("0");
        jPanel17.add(Conteo_User7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 50, 30));

        jPanel11.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 200, 90));

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Gestion8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Gestion8.setForeground(new java.awt.Color(127, 140, 141));
        Gestion8.setText("Hoteles");
        jPanel14.add(Gestion8, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 10, 110, 20));

        Conteo_User8.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        Conteo_User8.setForeground(new java.awt.Color(155, 89, 182));
        Conteo_User8.setText("0");
        jPanel14.add(Conteo_User8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 50, 30));

        jPanel11.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 200, 90));

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Gestion9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Gestion9.setForeground(new java.awt.Color(127, 140, 141));
        Gestion9.setText("Cafeterías");
        jPanel15.add(Gestion9, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 10, 110, 20));

        Conteo_User9.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        Conteo_User9.setForeground(new java.awt.Color(155, 89, 182));
        Conteo_User9.setText("0");
        jPanel15.add(Conteo_User9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 50, 30));

        jPanel11.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 200, 90));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 330, 460, 420));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/flecha-correcta (1).png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 270, 30, 20));

        Ges.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Ges.setForeground(new java.awt.Color(255, 249, 240));
        Ges.setText("Ver más detalles");
        jPanel1.add(Ges, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 268, -1, -1));

        Gestionar.setForeground(new java.awt.Color(255, 249, 240));
        Gestionar.setBorderPainted(false);
        Gestionar.setContentAreaFilled(false);
        Gestionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Gestionar.setFocusPainted(false);
        jPanel1.add(Gestionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 264, 240, 30));

        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Mis.png"))); // NOI18N
        jPanel18.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 80, 50));

        Comercial1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Comercial1.setForeground(new java.awt.Color(44, 62, 80));
        Comercial1.setText("Análisis de Reseñas");
        jPanel18.add(Comercial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        Mis.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Mis.setText("Mis acciones");
        jPanel18.add(Mis, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 16, -1, -1));

        jButton1.setText("Administrar reseñas");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel18.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 170, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/cerrar-sesion (1).png"))); // NOI18N
        jPanel18.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 60, 60));

        jButton2.setText("Salir");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jPanel18.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 170, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/lapiz (1).png"))); // NOI18N
        jPanel18.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 60, 60));

        jPanel1.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 590, 700, 160));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Resenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Resenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Resenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Resenas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Resenas(true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AAA;
    private javax.swing.JLabel Comercial;
    private javax.swing.JLabel Comercial1;
    private javax.swing.JLabel Conteo_User;
    private javax.swing.JLabel Conteo_User1;
    private javax.swing.JLabel Conteo_User2;
    private javax.swing.JLabel Conteo_User3;
    private javax.swing.JLabel Conteo_User4;
    private javax.swing.JLabel Conteo_User6;
    private javax.swing.JLabel Conteo_User7;
    private javax.swing.JLabel Conteo_User8;
    private javax.swing.JLabel Conteo_User9;
    private javax.swing.JLabel Cuencanas;
    private javax.swing.JLabel Ges;
    private javax.swing.JLabel Gestion;
    private javax.swing.JLabel Gestion1;
    private javax.swing.JLabel Gestion2;
    private javax.swing.JLabel Gestion3;
    private javax.swing.JLabel Gestion4;
    private javax.swing.JLabel Gestion6;
    private javax.swing.JLabel Gestion7;
    private javax.swing.JLabel Gestion8;
    private javax.swing.JLabel Gestion9;
    private javax.swing.JButton Gestionar;
    private javax.swing.JLabel Huellas;
    private javax.swing.JLabel Mis;
    private javax.swing.JLabel Muse5;
    private javax.swing.JLabel Museos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
