/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Animations.Animator;
import java.awt.Font;
import Design.RoundedButtonRegistrarseInicio;
import Design.RoundedButtonIniciarSesionRegistrarse;

/**
 *
 * @author USER
 */
public class Ventana_Bienvenida extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Bienvenida
     */
    public Ventana_Bienvenida() {
              setUndecorated(true);

        setOpacity(0f);
        initComponents();
     //Darle bordes redondeados a la ventana:
        setShape(new java.awt.geom.RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 60, 60));
        
        //Fuentes:
         Huellas.setFont(new Font("Open Sans Bold", Font.PLAIN, 11));
        Cuencanas.setFont(new Font("Open Sans", Font.PLAIN, 11));
        Descubra.setFont(new Font("CocogooseProTrial", Font.PLAIN, 39));
           turísticos.setFont(new Font("Caviar Dreams", Font.PLAIN, 39));
              Explora.setFont(new Font("Caviar Dreams", Font.PLAIN, 25));
                atractivos.setFont(new Font("Caviar Dreams", Font.PLAIN, 25));
                ciudad.setFont(new Font("Caviar Dreams", Font.PLAIN, 25));
                        IniciarSesion.setFont(new Font("Open Sans", Font.PLAIN, 14));
                        IniciarSesion1.setFont(new Font("Open Sans", Font.PLAIN, 14));


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Huellas = new javax.swing.JLabel();
        Cuencanas = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Descubra = new javax.swing.JLabel();
        turísticos = new javax.swing.JLabel();
        Explora = new javax.swing.JLabel();
        ciudad = new javax.swing.JLabel();
        atractivos = new javax.swing.JLabel();
        IniciarSesion = new RoundedButtonRegistrarseInicio("");
        IniciarSesion1 = new RoundedButtonIniciarSesionRegistrarse("");
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Huellas.setForeground(new java.awt.Color(255, 255, 255));
        Huellas.setText("Huellas ");
        jPanel1.add(Huellas, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 30, -1, -1));

        Cuencanas.setForeground(new java.awt.Color(255, 255, 255));
        Cuencanas.setText("Cuencanas");
        jPanel1.add(Cuencanas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 46, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Copilot_20250610_114322 (3).png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 70));

        Descubra.setForeground(new java.awt.Color(255, 255, 255));
        Descubra.setText("Descubra lugares ");
        jPanel1.add(Descubra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        turísticos.setForeground(new java.awt.Color(255, 255, 255));
        turísticos.setText("turísticos en Cuenca");
        jPanel1.add(turísticos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        Explora.setForeground(new java.awt.Color(255, 255, 255));
        Explora.setText("Explora los destinos más destacados");
        jPanel1.add(Explora, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        ciudad.setForeground(new java.awt.Color(255, 255, 255));
        ciudad.setText("Cuenca.");
        jPanel1.add(ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        atractivos.setForeground(new java.awt.Color(255, 255, 255));
        atractivos.setText("y atractivos de la ciudad de ");
        jPanel1.add(atractivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        IniciarSesion.setText("Registrarse");
        IniciarSesion.setBorderPainted(false);
        IniciarSesion.setContentAreaFilled(false);
        IniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IniciarSesion.setFocusPainted(false);
        IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(IniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 160, 40));

        IniciarSesion1.setText("Iniciar Sesión");
        IniciarSesion1.setBorderPainted(false);
        IniciarSesion1.setContentAreaFilled(false);
        IniciarSesion1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IniciarSesion1.setFocusPainted(false);
        IniciarSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesion1ActionPerformed(evt);
            }
        });
        jPanel1.add(IniciarSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 160, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Humano1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 400, 270));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Imagen Fondo Bienvenida.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 570));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionActionPerformed
  Animator.fadeOut(this, () -> {
          Registro miR = new Registro();
            Animator.fadeIn(miR);
        }); 


    }//GEN-LAST:event_IniciarSesionActionPerformed

    private void IniciarSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesion1ActionPerformed
  Animator.fadeOut(this, () -> {
          Login miR = new Login();
            Animator.fadeIn(miR);
        }); 


    }//GEN-LAST:event_IniciarSesion1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Bienvenida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cuencanas;
    private javax.swing.JLabel Descubra;
    private javax.swing.JLabel Explora;
    private javax.swing.JLabel Huellas;
    private javax.swing.JButton IniciarSesion;
    private javax.swing.JButton IniciarSesion1;
    private javax.swing.JLabel atractivos;
    private javax.swing.JLabel ciudad;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel turísticos;
    // End of variables declaration//GEN-END:variables
}
