/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Design.RoundedButtonEliminarRe;
import Design.RoundedButtonInsertar;
import Modelo.IglesiaDAO;
import Modelo.MuseoDAO;
import Modelo.RestauranteDAO;
import Modelo.UsuarioDAO;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import raven.glasspanepopup.GlassPanePopup;
import java.sql.SQLException;
import javax.swing.JFrame;

/**
 *
 * @author USER
 */
public class Ventana_EliminarRestaurante extends javax.swing.JPanel {

    private Ventana_UsuarioPrincipal ventanaPrincipal;
    private Ventana_AdministrarRestaurantes ventanaPadre;
    private int idRestaurante;

    /**
     * Creates new form Ventana_EliminarUsuarioPrincipal
     */
    public Ventana_EliminarRestaurante(Ventana_AdministrarRestaurantes padre) {
        initComponents();
        this.ventanaPadre = padre;

        //Fuentes:
        Eliminar.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 25));
        Esta.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 25));
        lblNombre.setFont(new Font("Segoe UI Light", Font.PLAIN, 20));
        lblId.setFont(new Font("Segoe UI Light", Font.PLAIN, 20));
        nombre.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 15));
        id.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 15));

    }

    //Darle fondo redondeado al Popup:
    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 25, 25));
        g2.dispose();
        super.paintComponent(grphcs);
    }

    public void setLabelNombre(String nombre) {
        lblNombre.setText(nombre);
    }

    public void setLabelId(String id) {
        lblId.setText(id);
    }

    public void setIdMuseo(int id) {
        this.idRestaurante = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Eliminar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Esta = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        EliminarUser = new RoundedButtonInsertar("");
        Cancelar = new RoundedButtonEliminarRe("");

        setPreferredSize(new java.awt.Dimension(623, 350));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(234, 45, 65));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        Eliminar.setText("Eliminar Restaurante");
        jPanel1.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Eliminar Museo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 50, 70));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 90));

        Esta.setForeground(new java.awt.Color(0, 0, 0));
        Esta.setText("¿Está seguro de eliminar a?");
        add(Esta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));
        add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 220, 30));
        add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 110, 20));

        nombre.setText("Nombre");
        add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 210, 130, -1));

        id.setText("Id");
        add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 30, -1));

        EliminarUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EliminarUser.setText("Eliminar");
        EliminarUser.setBorderPainted(false);
        EliminarUser.setContentAreaFilled(false);
        EliminarUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EliminarUser.setFocusPainted(false);
        EliminarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUserActionPerformed(evt);
            }
        });
        add(EliminarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 130, 40));

        Cancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.setBorderPainted(false);
        Cancelar.setContentAreaFilled(false);
        Cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cancelar.setFocusPainted(false);
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 130, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        GlassPanePopup.closePopupLast();


    }//GEN-LAST:event_CancelarActionPerformed

    private void EliminarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUserActionPerformed
        try {
            RestauranteDAO dao = new RestauranteDAO();
            System.out.println("ID que se va a eliminar: " + idRestaurante);
            boolean eliminado = dao.eliminarNegociosCompleto(idRestaurante);
            if (eliminado) {
                JOptionPane.showMessageDialog(null, "Restaurante eliminado correctamente.");
                GlassPanePopup.closePopupLast();
                ventanaPadre.recargarTablaMuseos();
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró el restaurante a eliminar.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al eliminar: " + e.getMessage());
        }


    }//GEN-LAST:event_EliminarUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel Eliminar;
    private javax.swing.JButton EliminarUser;
    private javax.swing.JLabel Esta;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
