/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Design.RoundedButtonAgregarImagenes;
import Design.RoundedButtonEliminarRe;
import Design.RoundedButtonInsertar;
import Design.RoundedPanelFecha;
import Design.RoundedPanelLateral;
import Design.RoundedText;
import Design.RoundedTextArea1;
import Design.RoundedTextField2;
import java.awt.BasicStroke;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Insets;
import java.awt.RenderingHints;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import raven.glasspanepopup.GlassPanePopup;
import Controlador.ControladorIglesia;
import Controlador.ControladorMuseo;
import Controlador.ControladorParque;
import Design.Imagen.ImagenUtils;
import java.sql.SQLException;
import javax.swing.JFrame;

/**
 *
 * @author USER
 */
public class Ventana_InsertarParque extends javax.swing.JPanel {

    private JTextArea textArea;
    private byte[] imagenBytes1;
    private byte[] imagenBytes2;
    private byte[] imagenBytes3;
    private Controlador.ControladorIglesia controlador;

    
    /**
     * Creates new form Ventana_InsertarIglesia
     */
    public Ventana_InsertarParque() {
        initComponents();

        //Fuentes:
        Registro.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 30));
        Categorias1.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 20));
        NomLugar.setFont(new Font("Segoe UI Light", Font.PLAIN, 15));
        Descrip.setFont(new Font("Segoe UI Light", Font.PLAIN, 15));
        Categorias2.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 20));
        Longi.setFont(new Font("Segoe UI Light", Font.PLAIN, 15));
        Direcc1.setFont(new Font("Segoe UI Light", Font.PLAIN, 15));
        Lati.setFont(new Font("Segoe UI Light", Font.PLAIN, 15));
        Categorias3.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 20));
        Vis1.setFont(new Font("Segoe UI Light", Font.PLAIN, 15));
        Vis2.setFont(new Font("Segoe UI Light", Font.PLAIN, 15));
        Vis3.setFont(new Font("Segoe UI Light", Font.PLAIN, 15));
        Categorias4.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 20));
        HoraApe.setFont(new Font("Segoe UI Light", Font.PLAIN, 15));
        HoraCierre.setFont(new Font("Segoe UI Light", Font.PLAIN, 15));
        NombreLugar.setFont(new Font("Segoe UI Light", Font.PLAIN, 16));
        DescripcionHistorica.setFont(new Font("Segoe UI Light", Font.PLAIN, 16));
        Direccion.setFont(new Font("Segoe UI Light", Font.PLAIN, 16));
        Latitud.setFont(new Font("Segoe UI Light", Font.PLAIN, 16));
        Longitud.setFont(new Font("Segoe UI Light", Font.PLAIN, 16));
        EntidadGestora.setFont(new Font("Segoe UI Light", Font.PLAIN, 16));
        Superficie.setFont(new Font("Segoe UI Light", Font.PLAIN, 16));
        Superficie.setFont(new Font("Segoe UI Light", Font.PLAIN, 16));
        Ejem1.setFont(new Font("Segoe UI Light", Font.PLAIN, 12));
        Ejem2.setFont(new Font("Segoe UI Light", Font.PLAIN, 12));
        Ejem3.setFont(new Font("Segoe UI Light", Font.PLAIN, 12));
        Ejem4.setFont(new Font("Segoe UI Light", Font.PLAIN, 12));
        Ejem5.setFont(new Font("Segoe UI Light", Font.PLAIN, 12));
        Ejem6.setFont(new Font("Segoe UI Light", Font.PLAIN, 12));
        Ejem7.setFont(new Font("Segoe UI Light", Font.PLAIN, 12));
        Ejem8.setFont(new Font("Segoe UI Light", Font.PLAIN, 12));

        //Crear el TextArea:
        this.textArea = new JTextArea();
        textArea.setBackground(new Color(224, 224, 224));
        textArea.setBorder(BorderFactory.createEmptyBorder());
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);
        textArea.setFont(new Font("Segoe UI Light", Font.PLAIN, 16));

        JScrollPane scrollPane = new JScrollPane(textArea);
        scrollPane.setBorder(new RoundedText());
        scrollPane.setPreferredSize(new Dimension(410, 50));

        DescripcionHistorica.setLayout(new BorderLayout());
        DescripcionHistorica.add(scrollPane, BorderLayout.CENTER);
        DescripcionHistorica.revalidate();
        DescripcionHistorica.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Registro = new javax.swing.JLabel();
        jPanel3 = new RoundedPanelLateral();
        Categorias1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        NomLugar = new javax.swing.JLabel();
        NombreLugar = new RoundedTextField2(20);
        DescripcionHistorica = new javax.swing.JPanel();
        Descrip = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new RoundedPanelLateral();
        jLabel4 = new javax.swing.JLabel();
        Categorias2 = new javax.swing.JLabel();
        Longi = new javax.swing.JLabel();
        Longitud = new RoundedTextField2(20);
        Direcc1 = new javax.swing.JLabel();
        Latitud = new RoundedTextField2(20);
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Lati = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Direccion = new RoundedTextField2(20);
        Ejem3 = new javax.swing.JLabel();
        Ejem1 = new javax.swing.JLabel();
        Ejem2 = new javax.swing.JLabel();
        Ejem6 = new javax.swing.JLabel();
        jPanel4 = new RoundedPanelLateral();
        Categorias3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        Vis1 = new javax.swing.JLabel();
        Vis2 = new javax.swing.JLabel();
        Vis3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CargarImagen = new RoundedButtonAgregarImagenes("");
        roundedImageLabel1 = new Design.Imagen.RoundedImageLabel();
        roundedImageLabel2 = new Design.Imagen.RoundedImageLabel();
        roundedImageLabel3 = new Design.Imagen.RoundedImageLabel();
        jPanel5 = new RoundedPanelLateral();
        jLabel12 = new javax.swing.JLabel();
        Categorias4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        HoraApe = new javax.swing.JLabel();
        Superficie = new RoundedTextField2(20);
        HoraCierre = new javax.swing.JLabel();
        EntidadGestora = new RoundedTextField2(20);
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new RoundedButtonEliminarRe("");
        Guardar = new RoundedButtonInsertar("");
        jButton4 = new javax.swing.JButton();
        Ejem5 = new javax.swing.JLabel();
        Ejem4 = new javax.swing.JLabel();
        Ejem7 = new javax.swing.JLabel();
        Ejem8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(252, 248, 248));
        setPreferredSize(new java.awt.Dimension(1350, 750));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(25, 162, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Arbol 1.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 60, 60));

        Registro.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Registro.setForeground(new java.awt.Color(255, 255, 255));
        Registro.setText("Registro de Parques");
        jPanel1.add(Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 26, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 100));

        jPanel3.setBackground(new java.awt.Color(248, 249, 250));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Categorias1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Categorias1.setForeground(new java.awt.Color(44, 62, 80));
        Categorias1.setText("Datos Generales");
        jPanel3.add(Categorias1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 16, 210, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Básico.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 50, 40));

        jSeparator1.setForeground(new java.awt.Color(224, 224, 224));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 410, 10));

        NomLugar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        NomLugar.setForeground(new java.awt.Color(44, 62, 80));
        NomLugar.setText("Nombre del Lugar");
        jPanel3.add(NomLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        NombreLugar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NombreLugar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreLugarKeyTyped(evt);
            }
        });
        jPanel3.add(NombreLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 410, 40));
        jPanel3.add(DescripcionHistorica, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 410, 50));

        Descrip.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Descrip.setForeground(new java.awt.Color(44, 62, 80));
        Descrip.setText("Descripción Histórica");
        jPanel3.add(Descrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("*");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 196, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 96, -1, -1));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 500, 310));

        jPanel2.setBackground(new java.awt.Color(248, 249, 250));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Ubication.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 50, 40));

        Categorias2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Categorias2.setForeground(new java.awt.Color(44, 62, 80));
        Categorias2.setText("Ubicación Geográfica");
        jPanel2.add(Categorias2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 16, 210, 40));

        Longi.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Longi.setForeground(new java.awt.Color(44, 62, 80));
        Longi.setText("Longitud");
        jPanel2.add(Longi, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        Longitud.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Longitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LongitudKeyTyped(evt);
            }
        });
        jPanel2.add(Longitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 180, 40));

        Direcc1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Direcc1.setForeground(new java.awt.Color(44, 62, 80));
        Direcc1.setText("Dirección");
        jPanel2.add(Direcc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        Latitud.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Latitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LatitudKeyTyped(evt);
            }
        });
        jPanel2.add(Latitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 180, 40));

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("*");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 186, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("*");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 86, -1, -1));

        Lati.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Lati.setForeground(new java.awt.Color(44, 62, 80));
        Lati.setText("Latitud");
        jPanel2.add(Lati, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("*");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 186, -1, -1));

        Direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 410, 40));

        Ejem3.setForeground(new java.awt.Color(127, 140, 141));
        Ejem3.setText("Ejemplo: ");
        jPanel2.add(Ejem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 273, -1, -1));

        Ejem1.setForeground(new java.awt.Color(127, 140, 141));
        Ejem1.setText("Ejemplo: ");
        jPanel2.add(Ejem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 273, -1, -1));

        Ejem2.setForeground(new java.awt.Color(44, 62, 80));
        Ejem2.setText("-12.43434");
        jPanel2.add(Ejem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 273, -1, -1));

        Ejem6.setForeground(new java.awt.Color(44, 62, 80));
        Ejem6.setText("-13.3232");
        jPanel2.add(Ejem6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 273, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 500, 310));

        jPanel4.setBackground(new java.awt.Color(248, 249, 250));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Categorias3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Categorias3.setForeground(new java.awt.Color(44, 62, 80));
        Categorias3.setText("Imágenes del Lugar");
        jPanel4.add(Categorias3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 16, 210, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Ima.png"))); // NOI18N
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 40));

        jSeparator2.setForeground(new java.awt.Color(224, 224, 224));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 640, 10));

        Vis1.setForeground(new java.awt.Color(44, 62, 80));
        Vis1.setText("Vista Previa");
        jPanel4.add(Vis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        Vis2.setForeground(new java.awt.Color(44, 62, 80));
        Vis2.setText("Vista Previa");
        jPanel4.add(Vis2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        Vis3.setForeground(new java.awt.Color(44, 62, 80));
        Vis3.setText("Vista Previa");
        jPanel4.add(Vis3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Ges.png"))); // NOI18N
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 30, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Agregar Imágenes");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 258, -1, -1));

        CargarImagen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CargarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarImagenActionPerformed(evt);
            }
        });
        jPanel4.add(CargarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 250, 40));
        jPanel4.add(roundedImageLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 210, 90));
        jPanel4.add(roundedImageLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 210, 90));
        jPanel4.add(roundedImageLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 210, 90));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 740, 310));

        jPanel5.setBackground(new java.awt.Color(248, 249, 250));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Info Paques.png"))); // NOI18N
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 40));

        Categorias4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Categorias4.setForeground(new java.awt.Color(44, 62, 80));
        Categorias4.setText("Información del Parque");
        jPanel5.add(Categorias4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 16, 320, 40));

        jSeparator3.setForeground(new java.awt.Color(224, 224, 224));
        jPanel5.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 640, 10));

        HoraApe.setForeground(new java.awt.Color(60, 63, 65));
        HoraApe.setText("Entidad Gestora");
        jPanel5.add(HoraApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 220, 30));

        Superficie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Superficie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SuperficieKeyTyped(evt);
            }
        });
        jPanel5.add(Superficie, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 290, 40));

        HoraCierre.setForeground(new java.awt.Color(60, 63, 65));
        HoraCierre.setText("Superficie en metros cuadrados");
        jPanel5.add(HoraCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 210, -1));

        EntidadGestora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EntidadGestora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EntidadGestoraKeyTyped(evt);
            }
        });
        jPanel5.add(EntidadGestora, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 290, 40));

        jLabel14.setBackground(new java.awt.Color(255, 102, 51));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cancelar");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 244, 140, 20));

        jLabel15.setBackground(new java.awt.Color(255, 102, 51));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Guardar");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 244, 110, 20));

        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 180, 30));

        Guardar.setBackground(new java.awt.Color(153, 0, 153));
        Guardar.setBorderPainted(false);
        Guardar.setContentAreaFilled(false);
        Guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Guardar.setFocusPainted(false);
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jPanel5.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 180, 30));

        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 150, 30));

        Ejem5.setForeground(new java.awt.Color(127, 140, 141));
        Ejem5.setText("Ejemplo: ");
        jPanel5.add(Ejem5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        Ejem4.setForeground(new java.awt.Color(44, 62, 80));
        Ejem4.setText("Alcaldia de Cuenca");
        jPanel5.add(Ejem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        Ejem7.setForeground(new java.awt.Color(127, 140, 141));
        Ejem7.setText("Ejemplo: ");
        jPanel5.add(Ejem7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        Ejem8.setForeground(new java.awt.Color(44, 62, 80));
        Ejem8.setText("30");
        jPanel5.add(Ejem8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, -1));

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 740, 310));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        GlassPanePopup.closePopupLast();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed

        try {
            if (NombreLugar.getText().trim().isEmpty()
                    || EntidadGestora.getText().trim().isEmpty()
                    || Superficie.getText().trim().isEmpty()
                    || Direccion.getText().trim().isEmpty()
                    || Latitud.getText().trim().isEmpty()
                    || Longitud.getText().trim().isEmpty()
                    || textArea.getText().trim().isEmpty()
                    || imagenBytes1 == null
                    || imagenBytes2 == null
                    || imagenBytes3 == null) {

                JOptionPane.showMessageDialog(this,
                        "Por favor, complete todos los campos y cargue las 3 imágenes.",
                        "Campos incompletos",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            String nombre = NombreLugar.getText().trim();
            String entidad_gestora = EntidadGestora.getText().trim();
            float superficie =  Float.parseFloat(Superficie.getText());
            String direccion = Direccion.getText().trim();
            double latitud = Double.parseDouble(Latitud.getText().trim());
            double longitud = Double.parseDouble(Longitud.getText().trim());
            String descripcion = textArea.getText().trim();

            byte[] img1 = imagenBytes1;
            byte[] img2 = imagenBytes2;
            byte[] img3 = imagenBytes3;

            ControladorParque ctrl = new ControladorParque();
            ctrl.guardarParque(
                    nombre,
                    entidad_gestora,
                    superficie,
                    direccion,
                    latitud,
                    longitud,
                    descripcion,
                    img1, img2, img3
            );

            Ventana_VerParques popup = new Ventana_VerParques();
            GlassPanePopup.showPopup(popup);

            limpiarFormulario();

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this,
                    "Latitud o longitud inválida.",
                    "Error de formato",
                    JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException iae) {
            JOptionPane.showMessageDialog(this,
                    iae.getMessage(),
                    "Validación",
                    JOptionPane.WARNING_MESSAGE);
        } catch (SQLException sqle) {
            JOptionPane.showMessageDialog(this,
                    "Error al guardar en la base:\n" + sqle.getMessage(),
                    "Error de base de datos",
                    JOptionPane.ERROR_MESSAGE);
            sqle.printStackTrace();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Error inesperado:\n" + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }


    }//GEN-LAST:event_GuardarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void CargarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarImagenActionPerformed

        byte[] datos = null;

        // Intentamos cargar en la primera ranura libre
        if (imagenBytes1 == null) {
            datos = ImagenUtils.seleccionarYConvertirImagen(roundedImageLabel1);
            imagenBytes1 = datos;
        } else if (imagenBytes2 == null) {
            datos = ImagenUtils.seleccionarYConvertirImagen(roundedImageLabel2);
            imagenBytes2 = datos;
        } else if (imagenBytes3 == null) {
            datos = ImagenUtils.seleccionarYConvertirImagen(roundedImageLabel3);
            imagenBytes3 = datos;
        } else {
            JOptionPane.showMessageDialog(this,
                    "Ya cargaste las 3 imágenes.",
                    "Carga de imagen",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        if (datos == null) {
            JOptionPane.showMessageDialog(this,
                    "No se cargó ninguna imagen.",
                    "Carga de imagen",
                    JOptionPane.WARNING_MESSAGE);

            if (imagenBytes1 == null) {
                roundedImageLabel1.setImagenDesdeBytes(null);
            } else if (imagenBytes2 == null) {
                roundedImageLabel2.setImagenDesdeBytes(null);
            } else if (imagenBytes3 == null) {
                roundedImageLabel3.setImagenDesdeBytes(null);
            }
        }


    }//GEN-LAST:event_CargarImagenActionPerformed

    private void EntidadGestoraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EntidadGestoraKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        // Permitir solo letras (mayúsculas y minúsculas) y espacios
        if (!Character.isLetter(c) && c != ' ') {
            evt.consume(); // Ignora el carácter si no es válido
        }

    }//GEN-LAST:event_EntidadGestoraKeyTyped

    private void NombreLugarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreLugarKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        // Permitir solo letras (mayúsculas y minúsculas) y espacios
        if (!Character.isLetter(c) && c != ' ') {
            evt.consume(); // Ignora el carácter si no es válido
        }
    }//GEN-LAST:event_NombreLugarKeyTyped

    private void SuperficieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SuperficieKeyTyped
        // TODO add your handling code here:
          char c = evt.getKeyChar();

        // Permitir dígitos
        if (Character.isDigit(c)) {
            return;
        }

        // Permitir un solo punto decimal, y no como primer carácter
        if (c == '.') {
            String texto = Superficie.getText();
            if (texto.contains(".") || texto.isEmpty()) {
                evt.consume(); // Ignora si ya hay un punto o si es el primer carácter
            }
            return;
        }
        // Ignorar cualquier otro carácter
        evt.consume();
    }//GEN-LAST:event_SuperficieKeyTyped

    private void LatitudKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LatitudKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String texto = Latitud.getText();

        // Permitir dígitos
        if (Character.isDigit(c)) {
            return;
        }

        // Permitir un solo punto decimal (y no al inicio)
        if (c == '.') {
            if (texto.contains(".") || texto.isEmpty() || (texto.equals("-"))) {
                evt.consume(); // Ignora si ya hay un punto, si es el primer carácter, o si solo hay el signo negativo
            }
            return;
        }

        // Permitir signo negativo solo como primer carácter
        if (c == '-') {
            if (!texto.isEmpty()) {
                evt.consume(); // Ignora si no es el primer carácter
            }
            return;
        }

        // Ignorar cualquier otro carácter
        evt.consume();
    }//GEN-LAST:event_LatitudKeyTyped

    private void LongitudKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LongitudKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String texto = Longitud.getText();

        // Permitir dígitos
        if (Character.isDigit(c)) {
            return;
        }

        // Permitir un solo punto decimal (y no al inicio)
        if (c == '.') {
            if (texto.contains(".") || texto.isEmpty() || (texto.equals("-"))) {
                evt.consume(); // Ignora si ya hay un punto, si es el primer carácter, o si solo hay el signo negativo
            }
            return;
        }

        // Permitir signo negativo solo como primer carácter
        if (c == '-') {
            if (!texto.isEmpty()) {
                evt.consume(); // Ignora si no es el primer carácter
            }
            return;
        }

        // Ignorar cualquier otro carácter
        evt.consume();
    }//GEN-LAST:event_LongitudKeyTyped

    private void limpiarFormulario() {
        NombreLugar.setText("");
        EntidadGestora.setText("");
        Superficie.setText("");
        Direccion.setText("");
        Latitud.setText("");
        Longitud.setText("");
        textArea.setText("");
        imagenBytes1 = imagenBytes2 = imagenBytes3 = null;
        roundedImageLabel1.setImagenDesdeBytes(null);
        roundedImageLabel2.setImagenDesdeBytes(null);
        roundedImageLabel3.setImagenDesdeBytes(null);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarImagen;
    private javax.swing.JLabel Categorias1;
    private javax.swing.JLabel Categorias2;
    private javax.swing.JLabel Categorias3;
    private javax.swing.JLabel Categorias4;
    private javax.swing.JLabel Descrip;
    private javax.swing.JPanel DescripcionHistorica;
    private javax.swing.JLabel Direcc1;
    private javax.swing.JTextField Direccion;
    private javax.swing.JLabel Ejem1;
    private javax.swing.JLabel Ejem2;
    private javax.swing.JLabel Ejem3;
    private javax.swing.JLabel Ejem4;
    private javax.swing.JLabel Ejem5;
    private javax.swing.JLabel Ejem6;
    private javax.swing.JLabel Ejem7;
    private javax.swing.JLabel Ejem8;
    private javax.swing.JTextField EntidadGestora;
    private javax.swing.JButton Guardar;
    private javax.swing.JLabel HoraApe;
    private javax.swing.JLabel HoraCierre;
    private javax.swing.JLabel Lati;
    private javax.swing.JTextField Latitud;
    private javax.swing.JLabel Longi;
    private javax.swing.JTextField Longitud;
    private javax.swing.JLabel NomLugar;
    private javax.swing.JTextField NombreLugar;
    private javax.swing.JLabel Registro;
    private javax.swing.JTextField Superficie;
    private javax.swing.JLabel Vis1;
    private javax.swing.JLabel Vis2;
    private javax.swing.JLabel Vis3;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private Design.Imagen.RoundedImageLabel roundedImageLabel1;
    private Design.Imagen.RoundedImageLabel roundedImageLabel2;
    private Design.Imagen.RoundedImageLabel roundedImageLabel3;
    // End of variables declaration//GEN-END:variables
}
