/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Design.RoundedButtonDetalles;
import Design.RoundedButtonInicio;
import Design.RoundedButtonLugares;
import Design.RoundedButtonRegresar;
import Design.RoundedPannelGris;
import Vista.PanelIglesias.Ventana_IglesiaElSagrario;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;


/**
 *
 * @author USER
 */
public class Ventana_Iglesias extends javax.swing.JFrame {
    private final String BusquedaText = "Buscar Iglesias";

    /**
     * Creates new form Interfaz_Lugares
     */
    public Ventana_Iglesias() {
        initComponents();
        
        //Fuentes:
        Busqueda2.setFont(new Font("Caviar Dreams", Font.PLAIN, 17));
        IglesiaSanBlas.setFont(new Font("CocogooseProTrial", Font.PLAIN, 15));
        Blas.setFont(new Font("Caviar Dreams", Font.PLAIN, 15));
        IglesiasLabel.setFont(new Font("CocogooseProTrial", Font.PLAIN, 13));
        Cuenca_Ecuador.setFont(new Font("CocogooseProTrial", Font.PLAIN, 13));
        estrellas1.setFont(new Font("Caviar Dreams", Font.PLAIN, 13));
        Iglesia.setFont(new Font("CocogooseProTrial", Font.PLAIN, 15));
        Sebastian.setFont(new Font("Caviar Dreams", Font.PLAIN, 15));
        IglesiasLabelSebastian.setFont(new Font("CocogooseProTrial", Font.PLAIN, 15));
        estrellas2.setFont(new Font("Caviar Dreams", Font.PLAIN, 13));
        Cuenca_Ecuador1.setFont(new Font("CocogooseProTrial", Font.PLAIN, 13));
        CatedralVieja1.setFont(new Font("CocogooseProTrial", Font.PLAIN, 15));
        Vieja1.setFont(new Font("Caviar Dreams", Font.PLAIN, 15));
        IglesiasLabel1.setFont(new Font("CocogooseProTrial", Font.PLAIN, 13));
        Cuenca_Ecuador2.setFont(new Font("CocogooseProTrial", Font.PLAIN, 13));
        estrellas3.setFont(new Font("Caviar Dreams", Font.PLAIN, 13));
        Iglesia1.setFont(new Font("CocogooseProTrial", Font.PLAIN, 15));
        Sebastian1.setFont(new Font("Caviar Dreams", Font.PLAIN, 15));
        IglesiasLabelSebastian1.setFont(new Font("CocogooseProTrial", Font.PLAIN, 15));
        Cuenca_Ecuador3.setFont(new Font("CocogooseProTrial", Font.PLAIN, 13));
        estrellas4.setFont(new Font("Caviar Dreams", Font.PLAIN, 13));
        IglesiaSanBlas1.setFont(new Font("CocogooseProTrial", Font.PLAIN, 15));
        Blas1.setFont(new Font("Caviar Dreams", Font.PLAIN, 15));
        IglesiasLabel2.setFont(new Font("CocogooseProTrial", Font.PLAIN, 13));
        Cuenca_Ecuador4.setFont(new Font("CocogooseProTrial", Font.PLAIN, 13));
        estrellas5.setFont(new Font("Caviar Dreams", Font.PLAIN, 13));
        Parques.setFont(new Font("Caviar Dreams", Font.PLAIN, 17));
        Regresar2.setFont(new Font("CocogooseProTrial", Font.PLAIN, 14));

        //Hacer invisible el JTextField de Búsqueda:
        Busqueda2.setOpaque(false);
        Busqueda2.setBorder(null);
        Busqueda2.setForeground(Color.BLACK);

        //Hacer el Holder para la búsqueda:
        ponerPlaceholder(Busqueda2, BusquedaText);

    }

    private void ponerPlaceholder(JTextField campo, String textoPorDefecto) {
        campo.setText(textoPorDefecto);
        campo.setForeground(Color.GRAY);

        campo.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (campo.getText().equals(textoPorDefecto)) {
                    campo.setText("");
                    campo.setForeground(new Color(160, 160, 160));
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (campo.getText().isEmpty()) {
                    campo.setForeground(Color.GRAY);
                    campo.setText(textoPorDefecto);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new RoundedPannelGris();
        Busqueda2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Estrellas1 = new javax.swing.JButton();
        jButton1 = new RoundedButtonLugares("");
        IglesiaSanBlas = new javax.swing.JLabel();
        Blas = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        IglesiasLabel = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Cuenca_Ecuador = new javax.swing.JLabel();
        jButton8 = new RoundedButtonDetalles("");
        jButton2 = new RoundedButtonLugares("");
        estrellas1 = new javax.swing.JLabel();
        Iglesia = new javax.swing.JLabel();
        Sebastian = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        IglesiasLabelSebastian = new javax.swing.JLabel();
        estrellas2 = new javax.swing.JLabel();
        Estrellas2 = new javax.swing.JButton();
        jButton9 = new RoundedButtonDetalles("");
        jLabel21 = new javax.swing.JLabel();
        Cuenca_Ecuador1 = new javax.swing.JLabel();
        jButton3 = new RoundedButtonLugares("");
        CatedralVieja1 = new javax.swing.JLabel();
        Vieja1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        IglesiasLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Cuenca_Ecuador2 = new javax.swing.JLabel();
        estrellas3 = new javax.swing.JLabel();
        Estrellas3 = new javax.swing.JButton();
        jButton10 = new RoundedButtonDetalles("");
        jButton5 = new RoundedButtonLugares("");
        Iglesia1 = new javax.swing.JLabel();
        Sebastian1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        IglesiasLabelSebastian1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Cuenca_Ecuador3 = new javax.swing.JLabel();
        estrellas4 = new javax.swing.JLabel();
        Estrellas4 = new javax.swing.JButton();
        jButton11 = new RoundedButtonDetalles("");
        jButton4 = new javax.swing.JButton();
        IglesiaSanBlas1 = new javax.swing.JLabel();
        Blas1 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        IglesiasLabel2 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Cuenca_Ecuador4 = new javax.swing.JLabel();
        estrellas5 = new javax.swing.JLabel();
        Estrellas5 = new javax.swing.JButton();
        jButton12 = new RoundedButtonDetalles("");
        jButton6 = new javax.swing.JButton();
        Parques = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Regresar2 = new javax.swing.JLabel();
        Regresar = new RoundedButtonRegresar("");
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1140, 830));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setBackground(new java.awt.Color(242, 242, 242));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        content.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 30, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Salir (2) (2).png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        content.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 16, 30, 40));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(Busqueda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 480, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Lupa__Ícono_-removebg-preview (1).png"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -14, 48, 80));

        content.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 560, 50));

        Estrellas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/5 estrellas.png"))); // NOI18N
        Estrellas1.setBorderPainted(false);
        Estrellas1.setContentAreaFilled(false);
        Estrellas1.setFocusPainted(false);
        content.add(Estrellas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 681, 180, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Catedral Vieja (1).jpg"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        content.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 340, 180));

        IglesiaSanBlas.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        IglesiaSanBlas.setForeground(new java.awt.Color(237, 79, 31));
        IglesiaSanBlas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IglesiaSanBlas.setText("Iglesia San");
        content.add(IglesiaSanBlas, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, -1, -1));

        Blas.setText("Franciso.");
        content.add(Blas, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/iglesia (2).png"))); // NOI18N
        content.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 666, -1, -1));

        IglesiasLabel.setText("Iglesias");
        content.add(IglesiasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 334, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/ubicacion (1).png"))); // NOI18N
        content.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 668, -1, -1));

        Cuenca_Ecuador.setText("Cuenca, Ecuador.");
        content.add(Cuenca_Ecuador, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 670, -1, -1));

        jButton8.setBackground(new java.awt.Color(204, 204, 204));
        jButton8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Ver Detalles");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        content.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 730, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Iglesia SanSebastián (1).jpg"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        content.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 444, 340, 170));

        estrellas1.setText("RATING:");
        content.add(estrellas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 693, -1, -1));

        Iglesia.setForeground(new java.awt.Color(237, 79, 31));
        Iglesia.setText("Iglesia de Todos");
        content.add(Iglesia, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 620, -1, -1));

        Sebastian.setText("Santos");
        content.add(Sebastian, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 640, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/iglesia (2).png"))); // NOI18N
        content.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, -1, -1));

        IglesiasLabelSebastian.setText("Iglesias");
        content.add(IglesiasLabelSebastian, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 670, -1, -1));

        estrellas2.setText("RATING:");
        content.add(estrellas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 360, -1, -1));

        Estrellas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/5 estrellas.png"))); // NOI18N
        Estrellas2.setBorderPainted(false);
        Estrellas2.setContentAreaFilled(false);
        Estrellas2.setFocusPainted(false);
        content.add(Estrellas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 350, 180, 40));

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Ver Detalles");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        content.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 396, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/ubicacion (1).png"))); // NOI18N
        content.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 330, -1, -1));

        Cuenca_Ecuador1.setText("Cuenca, Ecuador.");
        content.add(Cuenca_Ecuador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 334, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/IglesiaSanBlas (1).jpg"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        content.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 310, 180));

        CatedralVieja1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        CatedralVieja1.setForeground(new java.awt.Color(237, 79, 31));
        CatedralVieja1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CatedralVieja1.setText("Iglesia el Sagrario");
        content.add(CatedralVieja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        Vieja1.setText("(Catedral Vieja).");
        content.add(Vieja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/iglesia (2).png"))); // NOI18N
        content.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        IglesiasLabel1.setText("Iglesias");
        content.add(IglesiasLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 334, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/ubicacion (1).png"))); // NOI18N
        content.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        Cuenca_Ecuador2.setText("Cuenca, Ecuador.");
        content.add(Cuenca_Ecuador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 334, -1, -1));

        estrellas3.setText("RATING:");
        content.add(estrellas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        Estrellas3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/5 estrellas.png"))); // NOI18N
        Estrellas3.setBorderPainted(false);
        Estrellas3.setContentAreaFilled(false);
        Estrellas3.setFocusPainted(false);
        content.add(Estrellas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 356, 180, 40));

        jButton10.setBackground(new java.awt.Color(204, 204, 204));
        jButton10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Ver Detalles");
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        content.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/IglesiaTodosSantos (1).jpg"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusPainted(false);
        content.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 441, 310, 172));

        Iglesia1.setForeground(new java.awt.Color(237, 79, 31));
        Iglesia1.setText("Iglesia San");
        content.add(Iglesia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, -1, -1));

        Sebastian1.setText("Sebastián");
        content.add(Sebastian1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/iglesia (2).png"))); // NOI18N
        content.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, -1, -1));

        IglesiasLabelSebastian1.setText("Iglesias");
        content.add(IglesiasLabelSebastian1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 664, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/ubicacion (1).png"))); // NOI18N
        content.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 660, -1, -1));

        Cuenca_Ecuador3.setText("Cuenca, Ecuador.");
        content.add(Cuenca_Ecuador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 664, -1, -1));

        estrellas4.setText("RATING:");
        content.add(estrellas4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, -1, -1));

        Estrellas4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/5 estrellas.png"))); // NOI18N
        Estrellas4.setBorderPainted(false);
        Estrellas4.setContentAreaFilled(false);
        Estrellas4.setFocusPainted(false);
        content.add(Estrellas4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 678, 180, 40));

        jButton11.setBackground(new java.awt.Color(204, 204, 204));
        jButton11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Ver Detalles");
        jButton11.setContentAreaFilled(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        content.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 730, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/IglesiaSanFrancisco (1).jpg"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        content.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, 290, 180));

        IglesiaSanBlas1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        IglesiaSanBlas1.setForeground(new java.awt.Color(237, 79, 31));
        IglesiaSanBlas1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IglesiaSanBlas1.setText("Iglesia San");
        content.add(IglesiaSanBlas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, -1));

        Blas1.setText("Blas.");
        content.add(Blas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/iglesia (2).png"))); // NOI18N
        content.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, -1));

        IglesiasLabel2.setText("Iglesias");
        content.add(IglesiasLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 334, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/ubicacion (1).png"))); // NOI18N
        content.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, -1));

        Cuenca_Ecuador4.setText("Cuenca, Ecuador.");
        content.add(Cuenca_Ecuador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 334, -1, -1));

        estrellas5.setText("RATING:");
        content.add(estrellas5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 368, -1, -1));

        Estrellas5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/5 estrellas.png"))); // NOI18N
        Estrellas5.setBorderPainted(false);
        Estrellas5.setContentAreaFilled(false);
        Estrellas5.setFocusPainted(false);
        content.add(Estrellas5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 348, 180, 40));

        jButton12.setBackground(new java.awt.Color(204, 204, 204));
        jButton12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Ver Detalles");
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        content.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 394, -1, -1));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/siguiente-boton__3_-removebg-preview.png"))); // NOI18N
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setFocusPainted(false);
        content.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 450, 170, 170));

        Parques.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        Parques.setText("Mostrar más resultados");
        content.add(Parques, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 620, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/hogar (3).png"))); // NOI18N
        content.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 700, 50, 50));

        Regresar2.setForeground(new java.awt.Color(255, 255, 255));
        Regresar2.setText("Regresar al Menú Principal");
        content.add(Regresar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 720, -1, -1));

        Regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        content.add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 700, 300, 50));
        content.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1070, 760));

        jPanel1.setLayout(new java.awt.GridLayout(0, 3));
        content.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1070, 760));

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1180, 860));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir?", "Exit", dialog);
        if (result == 0) {
            System.exit(0);
        }

    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
   Ventana_Principal ventana = (Ventana_Principal) SwingUtilities.getWindowAncestor(this);
    ventana.mostrarPanelInicio();
           }//GEN-LAST:event_RegresarActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Ventana_IglesiaElSagrario MiLugar = new Ventana_IglesiaElSagrario();
        MiLugar.setSize(1140, 830);
        content.removeAll();
        content.add(MiLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 830));
        content.revalidate();
        content.repaint();

           }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Blas;
    private javax.swing.JLabel Blas1;
    private javax.swing.JTextField Busqueda2;
    private javax.swing.JLabel CatedralVieja1;
    private javax.swing.JLabel Cuenca_Ecuador;
    private javax.swing.JLabel Cuenca_Ecuador1;
    private javax.swing.JLabel Cuenca_Ecuador2;
    private javax.swing.JLabel Cuenca_Ecuador3;
    private javax.swing.JLabel Cuenca_Ecuador4;
    private javax.swing.JButton Estrellas1;
    private javax.swing.JButton Estrellas2;
    private javax.swing.JButton Estrellas3;
    private javax.swing.JButton Estrellas4;
    private javax.swing.JButton Estrellas5;
    private javax.swing.JLabel Iglesia;
    private javax.swing.JLabel Iglesia1;
    private javax.swing.JLabel IglesiaSanBlas;
    private javax.swing.JLabel IglesiaSanBlas1;
    private javax.swing.JLabel IglesiasLabel;
    private javax.swing.JLabel IglesiasLabel1;
    private javax.swing.JLabel IglesiasLabel2;
    private javax.swing.JLabel IglesiasLabelSebastian;
    private javax.swing.JLabel IglesiasLabelSebastian1;
    private javax.swing.JLabel Parques;
    private javax.swing.JButton Regresar;
    private javax.swing.JLabel Regresar2;
    private javax.swing.JLabel Sebastian;
    private javax.swing.JLabel Sebastian1;
    private javax.swing.JLabel Vieja1;
    private javax.swing.JPanel content;
    private javax.swing.JLabel estrellas1;
    private javax.swing.JLabel estrellas2;
    private javax.swing.JLabel estrellas3;
    private javax.swing.JLabel estrellas4;
    private javax.swing.JLabel estrellas5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
