/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Animations.Animator1;
import Design.RoundedButtonCeleste;
import Design.RoundedButtonNegocios;
import Design.RoundedButtonNegociosPanel;
import Design.RoundedPanelCafeterias;
import Design.RoundedPanelHabitaciones;
import Design.RoundedPanelHoteles;
import Design.RoundedPanelRestaurantes;
import Modelo.NegociosDAO;
import Modelo.PersonaDAO;
import java.awt.Font;

/**
 *
 * @author USER
 */
public class Ventana_Negocios extends javax.swing.JFrame {
    //Permitir entrar a la ventana:

    private boolean sinBordes = true;

    /**
     * Creates new form Ventana_Negocios
     */
    public Ventana_Negocios(boolean sinBordes) {

        if (sinBordes) {
            setUndecorated(true);
        }
        initComponents();
       CargarEstadisticasGenerales();
        //Fuentes:
        Huellas.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 20));
        Cuencanas.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 20));
        Button.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 15));
        Restaurantes.setFont(new Font("Segoe UI Light", Font.PLAIN, 15));
        Todos.setFont(new Font("Segoe UI Light", Font.PLAIN, 15));
        Cafeterias.setFont(new Font("Segoe UI Light", Font.PLAIN, 15));
        Hoteles.setFont(new Font("Segoe UI Light", Font.PLAIN, 15));
        Categoria.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 20));
        Hoteless.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 20));
        Gestion.setFont(new Font("Segoe UI Light", Font.PLAIN, 15));
        ConteoUser6.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 35));
        ConteoUser5.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 35));
        Registradas1.setFont(new Font("Segoe UI Light", Font.PLAIN, 12));
        Registradas1.setFont(new Font("Segoe UI Light", Font.PLAIN, 12));
        Restaurantes1.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 20));
        Gestion1.setFont(new Font("Segoe UI Light", Font.PLAIN, 15));
        ConteoUser7.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 35));
        ConteoUser8.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 35));
        Registradas3.setFont(new Font("Segoe UI Light", Font.PLAIN, 12));
        Registradas2.setFont(new Font("Segoe UI Light", Font.PLAIN, 12));
        Gestion2.setFont(new Font("Segoe UI Light", Font.PLAIN, 15));
        ConteoUser9.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 35));
        ConteoUser10.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 35));
        Registradas4.setFont(new Font("Segoe UI Light", Font.PLAIN, 12));
        Registradas5.setFont(new Font("Segoe UI Light", Font.PLAIN, 12));
        Hoteles.setFont(new Font("Segoe UI Light", Font.PLAIN, 12));
        GestionHoteles.setFont(new Font("Segoe UI Light", Font.PLAIN, 15));
        ConteoUser11.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 35));
        ConteoUser12.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 35));
        Registradas6.setFont(new Font("Segoe UI Light", Font.PLAIN, 12));
        Registradas7.setFont(new Font("Segoe UI Light", Font.PLAIN, 12));
        Gestion4.setFont(new Font("Segoe UI Light", Font.PLAIN, 15));
        ConteoUser13.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 35));
        ConteoUser14.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 35));
        Registradas8.setFont(new Font("Segoe UI Light", Font.PLAIN, 12));
        Registradas9.setFont(new Font("Segoe UI Light", Font.PLAIN, 12));
        AAA.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 20));
        hhh.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 20));
        GGG.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 20));

        //Extender la ventana al máximo: 
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        // Para pantalla completa:
        setExtendedState(Ventana_Principal.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        Huellas = new javax.swing.JLabel();
        Cuencanas = new javax.swing.JLabel();
        Restaurantes = new javax.swing.JLabel();
        Cafeterias = new javax.swing.JLabel();
        Hoteles = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Button = new RoundedButtonCeleste("");
        Todos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Button1 = new RoundedButtonCeleste("");
        Button2 = new RoundedButtonCeleste("");
        Button3 = new RoundedButtonCeleste("");
        Categoria = new javax.swing.JLabel();
        jPanel3 = new RoundedButtonNegocios();
        jLabel6 = new javax.swing.JLabel();
        Hoteless = new javax.swing.JLabel();
        Gestion = new javax.swing.JLabel();
        ConteoUser6 = new javax.swing.JLabel();
        ConteoUser5 = new javax.swing.JLabel();
        Registradas1 = new javax.swing.JLabel();
        Registradas = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Gestionar = new RoundedButtonNegociosPanel("");
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new RoundedPanelRestaurantes();
        jLabel8 = new javax.swing.JLabel();
        Restaurantes1 = new javax.swing.JLabel();
        Gestion1 = new javax.swing.JLabel();
        Registradas2 = new javax.swing.JLabel();
        ConteoUser7 = new javax.swing.JLabel();
        ConteoUser8 = new javax.swing.JLabel();
        Registradas3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Gestionar1 = new RoundedButtonNegociosPanel("");
        jPanel5 = new RoundedPanelCafeterias();
        jLabel10 = new javax.swing.JLabel();
        AAA = new javax.swing.JLabel();
        Gestion2 = new javax.swing.JLabel();
        ConteoUser9 = new javax.swing.JLabel();
        Registradas4 = new javax.swing.JLabel();
        ConteoUser10 = new javax.swing.JLabel();
        Registradas5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Gestionar2 = new RoundedButtonNegociosPanel("");
        jPanel6 = new RoundedPanelHoteles();
        jLabel12 = new javax.swing.JLabel();
        hhh = new javax.swing.JLabel();
        GestionHoteles = new javax.swing.JLabel();
        ConteoUser11 = new javax.swing.JLabel();
        ConteoUser12 = new javax.swing.JLabel();
        Registradas6 = new javax.swing.JLabel();
        Registradas7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Gestionar3 = new RoundedButtonNegociosPanel("");
        jPanel7 = new RoundedPanelHabitaciones();
        GGG = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Gestion4 = new javax.swing.JLabel();
        ConteoUser13 = new javax.swing.JLabel();
        ConteoUser14 = new javax.swing.JLabel();
        Registradas8 = new javax.swing.JLabel();
        Registradas9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Gestionar4 = new RoundedButtonNegociosPanel("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1390, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(248, 249, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(217, 188, 138));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Copilot_20250610_114322 (3).png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 60, 70));

        Huellas.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Huellas.setForeground(new java.awt.Color(255, 249, 240));
        Huellas.setText("Huellas ");
        jPanel2.add(Huellas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 26, -1, -1));

        Cuencanas.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Cuencanas.setForeground(new java.awt.Color(255, 255, 255));
        Cuencanas.setText("Cuencanas");
        jPanel2.add(Cuencanas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 48, -1, -1));

        Restaurantes.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Restaurantes.setForeground(new java.awt.Color(255, 249, 240));
        Restaurantes.setText("Restaurantes");
        jPanel2.add(Restaurantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 37, -1, -1));

        Cafeterias.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Cafeterias.setForeground(new java.awt.Color(255, 249, 240));
        Cafeterias.setText("Cafeterías");
        jPanel2.add(Cafeterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 37, -1, -1));

        Hoteles.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Hoteles.setForeground(new java.awt.Color(255, 249, 240));
        Hoteles.setText("Hoteles");
        jPanel2.add(Hoteles, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 37, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/llllll.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 40, 20, 20));

        Button.setForeground(new java.awt.Color(255, 249, 240));
        Button.setBorderPainted(false);
        Button.setContentAreaFilled(false);
        Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button.setFocusPainted(false);
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });
        jPanel2.add(Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 30, 170, 40));

        Todos.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Todos.setForeground(new java.awt.Color(255, 249, 240));
        Todos.setText("Todos");
        jPanel2.add(Todos, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 37, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/ssssssss.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 40, 30, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/zzzzzzzz.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 20, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Resta.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 20, 20));

        Button1.setForeground(new java.awt.Color(255, 249, 240));
        Button1.setBorderPainted(false);
        Button1.setContentAreaFilled(false);
        Button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button1.setFocusPainted(false);
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });
        jPanel2.add(Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 170, 40));

        Button2.setForeground(new java.awt.Color(255, 249, 240));
        Button2.setBorderPainted(false);
        Button2.setContentAreaFilled(false);
        Button2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button2.setFocusPainted(false);
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });
        jPanel2.add(Button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 170, 40));

        Button3.setForeground(new java.awt.Color(255, 249, 240));
        Button3.setBorderPainted(false);
        Button3.setContentAreaFilled(false);
        Button3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button3.setFocusPainted(false);
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });
        jPanel2.add(Button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, 170, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 100));

        Categoria.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Categoria.setForeground(new java.awt.Color(44, 62, 80));
        Categoria.setText("Gestión Comercial");
        jPanel1.add(Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Jotel.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 90));

        Hoteless.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Hoteless.setForeground(new java.awt.Color(44, 62, 80));
        Hoteless.setText("Negocios");
        jPanel3.add(Hoteless, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        Gestion.setForeground(new java.awt.Color(127, 140, 141));
        Gestion.setText("Gestión de Negocios.");
        jPanel3.add(Gestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 20));

        ConteoUser6.setFont(new java.awt.Font("Arial Black", 0, 35)); // NOI18N
        ConteoUser6.setForeground(new java.awt.Color(243, 156, 18));
        ConteoUser6.setText("0");
        ConteoUser6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(ConteoUser6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 90, 40));

        ConteoUser5.setFont(new java.awt.Font("Arial Black", 0, 35)); // NOI18N
        ConteoUser5.setForeground(new java.awt.Color(243, 156, 18));
        ConteoUser5.setText("0");
        ConteoUser5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(ConteoUser5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 90, 40));

        Registradas1.setForeground(new java.awt.Color(127, 140, 141));
        Registradas1.setText("Registrados");
        jPanel3.add(Registradas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        Registradas.setForeground(new java.awt.Color(127, 140, 141));
        Registradas.setText("Favoritos");
        jPanel3.add(Registradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/IIIIIIII.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 40, 30));

        Gestionar.setForeground(new java.awt.Color(255, 255, 255));
        Gestionar.setText("Gestionar");
        Gestionar.setBorderPainted(false);
        Gestionar.setContentAreaFilled(false);
        Gestionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Gestionar.setFocusPainted(false);
        jPanel3.add(Gestionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 170, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 270, 270));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 1320, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Comercial.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 90, 130));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/dddd.png"))); // NOI18N
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 90));

        Restaurantes1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Restaurantes1.setForeground(new java.awt.Color(44, 62, 80));
        Restaurantes1.setText("Restaurantes");
        jPanel4.add(Restaurantes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        Gestion1.setForeground(new java.awt.Color(127, 140, 141));
        Gestion1.setText("Lugares Gastronómicos.");
        jPanel4.add(Gestion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 20));

        Registradas2.setForeground(new java.awt.Color(127, 140, 141));
        Registradas2.setText("Favoritos");
        jPanel4.add(Registradas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        ConteoUser7.setFont(new java.awt.Font("Arial Black", 0, 35)); // NOI18N
        ConteoUser7.setForeground(new java.awt.Color(231, 76, 60));
        ConteoUser7.setText("0");
        ConteoUser7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(ConteoUser7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 90, 40));

        ConteoUser8.setFont(new java.awt.Font("Arial Black", 0, 35)); // NOI18N
        ConteoUser8.setForeground(new java.awt.Color(231, 76, 60));
        ConteoUser8.setText("0");
        ConteoUser8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(ConteoUser8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 90, 40));

        Registradas3.setForeground(new java.awt.Color(127, 140, 141));
        Registradas3.setText("Registrados");
        jPanel4.add(Registradas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/IIIIIIII.png"))); // NOI18N
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 40, 30));

        Gestionar1.setForeground(new java.awt.Color(255, 255, 255));
        Gestionar1.setText("Gestionar");
        Gestionar1.setBorderPainted(false);
        Gestionar1.setContentAreaFilled(false);
        Gestionar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Gestionar1.setFocusPainted(false);
        Gestionar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gestionar1ActionPerformed(evt);
            }
        });
        jPanel4.add(Gestionar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 170, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 270, 270));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Taza Cafe.png"))); // NOI18N
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 90));

        AAA.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        AAA.setForeground(new java.awt.Color(44, 62, 80));
        AAA.setText("Cafeterías");
        jPanel5.add(AAA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        Gestion2.setForeground(new java.awt.Color(127, 140, 141));
        Gestion2.setText("Gestión de cafeterías.");
        jPanel5.add(Gestion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 20));

        ConteoUser9.setFont(new java.awt.Font("Arial Black", 0, 35)); // NOI18N
        ConteoUser9.setForeground(new java.awt.Color(142, 68, 173));
        ConteoUser9.setText("0");
        ConteoUser9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5.add(ConteoUser9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 90, 40));

        Registradas4.setForeground(new java.awt.Color(127, 140, 141));
        Registradas4.setText("Registrados");
        jPanel5.add(Registradas4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        ConteoUser10.setFont(new java.awt.Font("Arial Black", 0, 35)); // NOI18N
        ConteoUser10.setForeground(new java.awt.Color(142, 68, 173));
        ConteoUser10.setText("0");
        ConteoUser10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5.add(ConteoUser10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 90, 40));

        Registradas5.setForeground(new java.awt.Color(127, 140, 141));
        Registradas5.setText("Favoritos");
        jPanel5.add(Registradas5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/IIIIIIII.png"))); // NOI18N
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 40, 30));

        Gestionar2.setForeground(new java.awt.Color(255, 255, 255));
        Gestionar2.setText("Gestionar");
        Gestionar2.setBorderPainted(false);
        Gestionar2.setContentAreaFilled(false);
        Gestionar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Gestionar2.setFocusPainted(false);
        Gestionar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gestionar2ActionPerformed(evt);
            }
        });
        jPanel5.add(Gestionar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 170, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 270, 270));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Jotel 2.png"))); // NOI18N
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 90));

        hhh.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        hhh.setForeground(new java.awt.Color(44, 62, 80));
        hhh.setText("Hoteles");
        jPanel6.add(hhh, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        GestionHoteles.setForeground(new java.awt.Color(127, 140, 141));
        GestionHoteles.setText("Gestión de Hoteles.");
        jPanel6.add(GestionHoteles, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 20));

        ConteoUser11.setFont(new java.awt.Font("Arial Black", 0, 35)); // NOI18N
        ConteoUser11.setForeground(new java.awt.Color(22, 160, 133));
        ConteoUser11.setText("0");
        ConteoUser11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel6.add(ConteoUser11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 90, 40));

        ConteoUser12.setFont(new java.awt.Font("Arial Black", 0, 35)); // NOI18N
        ConteoUser12.setForeground(new java.awt.Color(22, 160, 133));
        ConteoUser12.setText("0");
        ConteoUser12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel6.add(ConteoUser12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 90, 40));

        Registradas6.setForeground(new java.awt.Color(127, 140, 141));
        Registradas6.setText("Registrados");
        jPanel6.add(Registradas6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        Registradas7.setForeground(new java.awt.Color(127, 140, 141));
        Registradas7.setText("Favoritos");
        jPanel6.add(Registradas7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/IIIIIIII.png"))); // NOI18N
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 40, 30));

        Gestionar3.setForeground(new java.awt.Color(255, 255, 255));
        Gestionar3.setText("Gestionar");
        Gestionar3.setBorderPainted(false);
        Gestionar3.setContentAreaFilled(false);
        Gestionar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Gestionar3.setFocusPainted(false);
        jPanel6.add(Gestionar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 170, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 190, 270, 270));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GGG.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        GGG.setForeground(new java.awt.Color(44, 62, 80));
        GGG.setText("Habitaciones");
        jPanel7.add(GGG, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/HABI.png"))); // NOI18N
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 90));

        Gestion4.setForeground(new java.awt.Color(127, 140, 141));
        Gestion4.setText("Gestión de habitaciones.");
        jPanel7.add(Gestion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 20));

        ConteoUser13.setFont(new java.awt.Font("Arial Black", 0, 35)); // NOI18N
        ConteoUser13.setForeground(new java.awt.Color(52, 152, 219));
        ConteoUser13.setText("0");
        ConteoUser13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel7.add(ConteoUser13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 90, 40));

        ConteoUser14.setFont(new java.awt.Font("Arial Black", 0, 35)); // NOI18N
        ConteoUser14.setForeground(new java.awt.Color(52, 152, 219));
        ConteoUser14.setText("0");
        ConteoUser14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel7.add(ConteoUser14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 90, 40));

        Registradas8.setForeground(new java.awt.Color(127, 140, 141));
        Registradas8.setText("Registrados");
        jPanel7.add(Registradas8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        Registradas9.setForeground(new java.awt.Color(127, 140, 141));
        Registradas9.setText("Favoritos");
        jPanel7.add(Registradas9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/IIIIIIII.png"))); // NOI18N
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 40, 30));

        Gestionar4.setForeground(new java.awt.Color(255, 255, 255));
        Gestionar4.setText("Gestionar");
        Gestionar4.setBorderPainted(false);
        Gestionar4.setContentAreaFilled(false);
        Gestionar4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Gestionar4.setFocusPainted(false);
        jPanel7.add(Gestionar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 170, 30));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 270, 270));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button1ActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button2ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button3ActionPerformed

    private void Gestionar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gestionar1ActionPerformed
        // TODO add your handling code here:
        Animator1.fadeOut(this, () -> {
            this.dispose();

            Ventana_AdministrarRestaurantes ventana = new Ventana_AdministrarRestaurantes(this, true);
            ventana.setOpacity(0f);
            ventana.setVisible(true);

            Animator1.fadeIn(ventana);
        });
    }//GEN-LAST:event_Gestionar1ActionPerformed

    private void Gestionar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gestionar2ActionPerformed
        // TODO add your handling code here:
        Animator1.fadeOut(this, () -> {
            this.dispose();

            Ventana_AdministrarCafeterias ventana = new Ventana_AdministrarCafeterias(this, true);
            ventana.setOpacity(0f);
            ventana.setVisible(true);

            Animator1.fadeIn(ventana);
        });
    }//GEN-LAST:event_Gestionar2ActionPerformed
    public void CargarEstadisticasGenerales(){
      PersonaDAO persona =new PersonaDAO();
      NegociosDAO negocio =new NegociosDAO();
      int totalRestaurante = negocio.contarRestaurantes();
      int totalCafeteria = negocio.contarCafeterias();
      int totalNegocios = negocio.contarNegocios();
      ConteoUser6.setText(String.valueOf(totalNegocios));
      ConteoUser7.setText(String.valueOf(totalRestaurante));
      ConteoUser9.setText(String.valueOf(totalCafeteria));
      
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Negocios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Negocios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Negocios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Negocios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Negocios(true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AAA;
    private javax.swing.JButton Button;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JLabel Cafeterias;
    private javax.swing.JLabel Categoria;
    private javax.swing.JLabel ConteoUser10;
    private javax.swing.JLabel ConteoUser11;
    private javax.swing.JLabel ConteoUser12;
    private javax.swing.JLabel ConteoUser13;
    private javax.swing.JLabel ConteoUser14;
    private javax.swing.JLabel ConteoUser5;
    private javax.swing.JLabel ConteoUser6;
    private javax.swing.JLabel ConteoUser7;
    private javax.swing.JLabel ConteoUser8;
    private javax.swing.JLabel ConteoUser9;
    private javax.swing.JLabel Cuencanas;
    private javax.swing.JLabel GGG;
    private javax.swing.JLabel Gestion;
    private javax.swing.JLabel Gestion1;
    private javax.swing.JLabel Gestion2;
    private javax.swing.JLabel Gestion4;
    private javax.swing.JLabel GestionHoteles;
    private javax.swing.JButton Gestionar;
    private javax.swing.JButton Gestionar1;
    private javax.swing.JButton Gestionar2;
    private javax.swing.JButton Gestionar3;
    private javax.swing.JButton Gestionar4;
    private javax.swing.JLabel Hoteles;
    private javax.swing.JLabel Hoteless;
    private javax.swing.JLabel Huellas;
    private javax.swing.JLabel Registradas;
    private javax.swing.JLabel Registradas1;
    private javax.swing.JLabel Registradas2;
    private javax.swing.JLabel Registradas3;
    private javax.swing.JLabel Registradas4;
    private javax.swing.JLabel Registradas5;
    private javax.swing.JLabel Registradas6;
    private javax.swing.JLabel Registradas7;
    private javax.swing.JLabel Registradas8;
    private javax.swing.JLabel Registradas9;
    private javax.swing.JLabel Restaurantes;
    private javax.swing.JLabel Restaurantes1;
    private javax.swing.JLabel Todos;
    private javax.swing.JLabel hhh;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
