/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Design.RoundedTextField2;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author USER
 */
public class Ventana_Insertar_Lugar extends javax.swing.JPanel {

    /**
     * Creates new form Ventana_Insertar_Lugar
     */
    public Ventana_Insertar_Lugar() {
        setOpaque(false);

        initComponents();

        //Fuentes:
        Lugares.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 25));
        Nombre.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 16));
        Datos.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 18));
        Nombres.setFont(new Font("Segoe UI Light", Font.PLAIN, 16));

    }

    //Bordes redondeados al popup:
    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 50, 50));
        g2.dispose();
        super.paintComponent(grphcs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Lugares = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Datos = new javax.swing.JLabel();
        Nombres = new RoundedTextField2(20);

        setPreferredSize(new java.awt.Dimension(1200, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lugares.setForeground(new java.awt.Color(255, 255, 255));
        Lugares.setText("Insertar Lugar");
        jPanel1.add(Lugares, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Lugares 2.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, 70));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1300, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Info 2.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        Nombre.setForeground(new java.awt.Color(108, 117, 125));
        Nombre.setText("Nombre");
        add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        Datos.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Datos.setForeground(new java.awt.Color(44, 62, 80));
        Datos.setText("Datos Básicos");
        add(Datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 108, -1, -1));

        Nombres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(Nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 220, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Datos;
    private javax.swing.JLabel Lugares;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField Nombres;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
