/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Conexion.UserDAO;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import Conexion.ConexionPostgres;
import Conexion.UserDAO;
import Conexion.CodigoDAO;
import Conexion.ConexionPostgres;
import Design.RoundedBorder;
import Design.RoundedButton;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import Conexion.UserDAO;
import Conexion.TokenDAO;
import Conexion.EmailService;
import Conexion.UserDAO;
import java.sql.SQLException;
import jakarta.mail.MessagingException;
import javax.swing.*;        // si usas JOptionPane, JButton, etc.
import java.awt.event.*;

/**
 *
 * @author USER
 */
public class VentanaCambiarContrasenia extends javax.swing.JFrame {

    private String email;
    private String NuevaContrasenia1 = "Nueva Contraseña";
    private String ConfirmarContrasenia1 = "Confirmar Contraseña";

    /**
     * Creates new form VentanaCambiarContrasenia
     */
    public VentanaCambiarContrasenia(String email) {

        setUndecorated(true);
        setOpacity(1f);
        initComponents();
        this.email = email;
        setLocationRelativeTo(null); // Centrar ventana

        //Fuentes
        Recuperar.setFont(new Font("CocogooseProTrial", Font.PLAIN, 21));
        NuevaContrasenia.setFont(new Font("Caviar Dreams", Font.PLAIN, 16));
        ConfirmarContrasenia.setFont(new Font("Caviar Dreams", Font.PLAIN, 16));
        
        //Hacer Redondeada la Ventana:
        setShape(new java.awt.geom.RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 60, 60));

        //Darle Bordes y PlaceHolder a los TextField:   
        NuevaContrasenia.setBorder(new RoundedBorder(new Color(165, 170, 163), 2, 30, 30));
        NuevaContrasenia.setOpaque(false);

        ConfirmarContrasenia.setBorder(new RoundedBorder(new Color(165, 170, 163), 2, 30, 30));
        ConfirmarContrasenia.setOpaque(false);

        ponerPlaceholder(NuevaContrasenia, NuevaContrasenia1);
        ponerPlaceholder(ConfirmarContrasenia, ConfirmarContrasenia1);
    }

    private void ponerPlaceholder(javax.swing.JTextField campo, String textoPorDefecto) {
        campo.setText(textoPorDefecto);
        campo.setForeground(java.awt.Color.GRAY);

        campo.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (campo.getText().equals(textoPorDefecto)) {
                    campo.setText("");
                    campo.setForeground(new Color(0, 0, 0, 255));
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (campo.getText().isEmpty()) {
                    campo.setForeground(java.awt.Color.GRAY);
                    campo.setText(textoPorDefecto);
                }
            }
        });
    }

    private void ponerPlaceholder(javax.swing.JPasswordField campo, String textoPorDefecto) {
        campo.setEchoChar((char) 0);
        campo.setText(textoPorDefecto);
        campo.setForeground(java.awt.Color.GRAY);

        campo.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                String passText = new String(campo.getPassword());
                if (passText.equals(textoPorDefecto)) {
                    campo.setText("");
                    campo.setForeground(new Color(160, 160, 160));
                    campo.setEchoChar('•');
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                String passText = new String(campo.getPassword());
                if (passText.isEmpty()) {
                    campo.setEchoChar((char) 0);
                    campo.setForeground(java.awt.Color.GRAY);
                    campo.setText(textoPorDefecto);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new Design.RoundedPanel();
        jButton1 =  new RoundedButton("Entrar");
        NuevaContrasenia = new javax.swing.JTextField();
        Recuperar = new javax.swing.JLabel();
        ConfirmarContrasenia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        FondoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Continuar");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 130, 40));

        NuevaContrasenia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        NuevaContrasenia.setForeground(new java.awt.Color(0, 0, 0));
        NuevaContrasenia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NuevaContrasenia.setText("Correo electrónico:");
        NuevaContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaContraseniaActionPerformed(evt);
            }
        });
        jPanel3.add(NuevaContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 313, 54));

        Recuperar.setText("Recuperar Contraseña");
        jPanel3.add(Recuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 300, -1));

        ConfirmarContrasenia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ConfirmarContrasenia.setText("Confirmar Contraseña:");
        jPanel3.add(ConfirmarContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 310, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 380, 270));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 30, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Salir (2) (2).png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 6, 30, 40));

        FondoLogin.setForeground(new java.awt.Color(11, 187, 187));
        FondoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Fondo Login.png"))); // NOI18N
        getContentPane().add(FondoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nueva = NuevaContrasenia.getText().trim();
        String confirmar = ConfirmarContrasenia.getText().trim();

        if (!nueva.equals(confirmar)) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden.");
            return;
        }

        if (nueva.length() < 6) {
            JOptionPane.showMessageDialog(this, "La contraseña debe tener al menos 6 caracteres.");
            return;
        }

        try {
            boolean actualizado = UserDAO.actualizarContrasenia(email, nueva);
            if (actualizado) {
                JOptionPane.showMessageDialog(this, "Contraseña actualizada correctamente.");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar la contraseña.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void NuevaContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevaContraseniaActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        this.setState(RecuperarContrasenia.ICONIFIED);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir?", "Exit", dialog);
        if (result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    public static boolean actualizarContrasenia(String email, String nuevaContrasenia) throws SQLException {
        String sql = "UPDATE usuarios SET contrasenia = ? WHERE email = ?";
        try ( Connection conn = ConexionPostgres.conectar();  PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, nuevaContrasenia);
            ps.setString(2, email);
            return ps.executeUpdate() > 0;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ConfirmarContrasenia;
    private javax.swing.JLabel FondoLogin;
    private javax.swing.JTextField NuevaContrasenia;
    private javax.swing.JLabel Recuperar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
