/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Vista.VentanaCambiarContrasenia;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import Conexion.CodigoDAO;
import Conexion.CodigoDAO;
import Design.RoundedBorder;
import Design.RoundedButton;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author USER
 */
public class VentanaValidarCodigo extends javax.swing.JFrame {

    private String email;
    private javax.swing.JTextField txtCodigo;
    private String Correo_electronico = "Correo electronico";

    public VentanaValidarCodigo(String email) {
        initComponents();
        this.email = email;

        //Fuentes:
        Verificar.setFont(new Font("CocogooseProTrial", Font.PLAIN, 21));
        CodigoEnviado.setFont(new Font("Caviar Dreams", Font.PLAIN, 14));
        txtCodigoRecibido.setFont(new Font("Caviar Dreams", Font.PLAIN, 16));

        //Hacer la ventana redonda:
        setShape(new java.awt.geom.RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 60, 60));

        //Poner PlaceHolder al TextField y darle bordes:
        txtCodigoRecibido.setBorder(new RoundedBorder(new Color(165, 170, 163), 2, 30, 30));
        txtCodigoRecibido.setOpaque(false);

        ponerPlaceholder(txtCodigoRecibido, Correo_electronico);
    }

    private void ponerPlaceholder(javax.swing.JTextField campo, String textoPorDefecto) {
        campo.setText(textoPorDefecto);
        campo.setForeground(java.awt.Color.GRAY);

        campo.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (campo.getText().equals(textoPorDefecto)) {
                    campo.setText("");
                    campo.setForeground(new Color(0, 0, 0, 255));
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (campo.getText().isEmpty()) {
                    campo.setForeground(java.awt.Color.GRAY);
                    campo.setText(textoPorDefecto);
                }
            }
        });
    }

    private void ponerPlaceholder(javax.swing.JPasswordField campo, String textoPorDefecto) {
        campo.setEchoChar((char) 0);
        campo.setText(textoPorDefecto);
        campo.setForeground(java.awt.Color.GRAY);

        campo.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                String passText = new String(campo.getPassword());
                if (passText.equals(textoPorDefecto)) {
                    campo.setText("");
                    campo.setForeground(new Color(160, 160, 160));
                    campo.setEchoChar('•');
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                String passText = new String(campo.getPassword());
                if (passText.isEmpty()) {
                    campo.setEchoChar((char) 0);
                    campo.setForeground(java.awt.Color.GRAY);
                    campo.setText(textoPorDefecto);
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new Design.RoundedPanel();
        Continuar =  new RoundedButton("Entrar");
        txtCodigoRecibido = new javax.swing.JTextField();
        Verificar = new javax.swing.JLabel();
        CodigoEnviado = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        FondoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Continuar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Continuar.setText("Continuar");
        Continuar.setBorderPainted(false);
        Continuar.setContentAreaFilled(false);
        Continuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Continuar.setFocusPainted(false);
        Continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinuarActionPerformed(evt);
            }
        });
        jPanel3.add(Continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 130, 40));

        txtCodigoRecibido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCodigoRecibido.setForeground(new java.awt.Color(0, 0, 0));
        txtCodigoRecibido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigoRecibido.setText("Correo electrónico:");
        txtCodigoRecibido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoRecibidoActionPerformed(evt);
            }
        });
        jPanel3.add(txtCodigoRecibido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 313, 54));

        Verificar.setText("Verificar Código");
        jPanel3.add(Verificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 300, -1));

        CodigoEnviado.setText("Ingrese el código enviado a su correo:");
        jPanel3.add(CodigoEnviado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 380, 230));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 30, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Salir (2) (2).png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 6, 30, 40));

        FondoLogin.setForeground(new java.awt.Color(11, 187, 187));
        FondoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Fondo Login.png"))); // NOI18N
        getContentPane().add(FondoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinuarActionPerformed
        String codigoIngresado = txtCodigoRecibido.getText().trim();

        try {
            if (CodigoDAO.validarCodigo(email, codigoIngresado)) {
                JOptionPane.showMessageDialog(this, "Código correcto. Ahora puedes cambiar tu contraseña.");
                new VentanaCambiarContrasenia(email).setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Código incorrecto. Intenta de nuevo.");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error con la base de datos: " + ex.getMessage());
        }

    }//GEN-LAST:event_ContinuarActionPerformed

    private void txtCodigoRecibidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoRecibidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoRecibidoActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        this.setState(RecuperarContrasenia.ICONIFIED);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir?", "Exit", dialog);
        if (result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CodigoEnviado;
    private javax.swing.JButton Continuar;
    private javax.swing.JLabel FondoLogin;
    private javax.swing.JLabel Verificar;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCodigoRecibido;
    // End of variables declaration//GEN-END:variables
}
