/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Design.RoundedButtonFavoritosMensaje;
import Design.RoundedButtonFavoritosQuitar;
import java.awt.AWTEvent;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import raven.glasspanepopup.GlassPanePopup;

/**
 *
 * @author USER
 */
public class Ventana_QuitadoFavorito extends javax.swing.JPanel {

    /**
     * Creates new form Ventana_AgregadoFavorito
     */
    public Ventana_QuitadoFavorito() {
        initComponents();
        setOpaque(false);

        EventQueue queue = Toolkit.getDefaultToolkit().getSystemEventQueue();
        queue.push(new EventQueue() {
            @Override
            protected void dispatchEvent(AWTEvent event) {
                try {
                    super.dispatchEvent(event);
                } catch (NullPointerException npe) {

                    // Verificamos si el NPE viene de la librería GlassPanePopup
                    boolean isGlassPaneError = false;
                    for (StackTraceElement element : npe.getStackTrace()) {
                        if (element.getClassName().startsWith("raven.glasspanepopup")
                                || element.getClassName().contains("WindowSnapshots")
                                || element.getClassName().contains("Popup")) {
                            isGlassPaneError = true;
                            break;
                        }
                    }

                    if (isGlassPaneError) {
                        // Log opcional para debugging
                        System.err.println("NPE silenciado de GlassPanePopup: " + npe.getMessage());
                    } else {
                        // Si es otro NPE, lo relanzamos
                        throw npe;
                    }
                }
            }
        });
        //Fuentes:
        AGG.setFont(new Font("Open Sans Bold", Font.PLAIN, 25));
        Luga.setFont(new Font("Open Sans", Font.PLAIN, 14));
        fav.setFont(new Font("Open Sans", Font.PLAIN, 14));

    }

    //Para darle esos bordes:
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); // Limpia y pinta los componentes hijos primero

        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        // Fondo redondeado
        g2.setColor(getBackground());
        g2.fill(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 25, 25));

        g2.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AGG = new javax.swing.JLabel();
        Luga = new javax.swing.JLabel();
        fav = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new RoundedButtonFavoritosQuitar("");
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(370, 280));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AGG.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        AGG.setForeground(new java.awt.Color(51, 51, 51));
        AGG.setText("¡Quitado de Favoritos!");
        add(AGG, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        Luga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Luga.setForeground(new java.awt.Color(174, 174, 174));
        Luga.setText("Has quitado este lugar a tus lugares");
        add(Luga, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        fav.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fav.setForeground(new java.awt.Color(174, 174, 174));
        fav.setText("favoritos.");
        add(fav, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Quita Cora.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 30, 30));

        jButton1.setText("Entendido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 160, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Quitado Cora (2).png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 90, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            GlassPanePopup.closePopupLast();
        } catch (NullPointerException npe) {
            System.err.println("Error al cerrar popup: " + npe.getMessage());
        } catch (Exception ex) {
            // Otros errores
            System.err.println("Error general al cerrar popup: " + ex.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AGG;
    private javax.swing.JLabel Luga;
    private javax.swing.JLabel fav;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
