/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Design.RoundedPanelUser;
import java.awt.Font;
import Design.RoundedPanel;
import Design.ComboBox.Combobox;
import java.awt.Component;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import Design.RoundedButtonAceptarComentario;

/**
 *
 * @author USER
 */
public class Ventana_MisFavoritos extends javax.swing.JFrame {

    private String Provincia = "Filtrar por";

    /**
     * Creates new form Ventana_MisFavoritos
     */
    public Ventana_MisFavoritos() {
        initComponents();

        //Maximizar la ventana al máximo:
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setExtendedState(Ventana_Principal.MAXIMIZED_BOTH);
        
        //Fuentes:
        Favoritos.setFont(new Font("CocogooseProTrial", Font.PLAIN, 28));
        Guarda.setFont(new Font("Caviar Dreams", Font.PLAIN, 20));
        Usuario_Favoritos.setFont(new Font("Caviar Dreams", Font.PLAIN, 20));
        Favoritos1.setFont(new Font("Caviar Dreams Bold", Font.PLAIN, 20));
        HotelYanun.setFont(new Font("CocogooseProTrial", Font.PLAIN, 18));
        Quitar.setFont(new Font("Caviar Dreams", Font.PLAIN, 14));
        Detalles.setFont(new Font("Caviar Dreams", Font.PLAIN, 14));
        IglesiaSan.setFont(new Font("CocogooseProTrial", Font.PLAIN, 18));
        Quitar1.setFont(new Font("Caviar Dreams", Font.PLAIN, 14));
        Detalles1.setFont(new Font("Caviar Dreams", Font.PLAIN, 14));
        IglesiaSanBlas.setFont(new Font("CocogooseProTrial", Font.PLAIN, 18));
        Quitar2.setFont(new Font("Caviar Dreams", Font.PLAIN, 14));
        Detalles2.setFont(new Font("Caviar Dreams", Font.PLAIN, 14));
        IglesiaTodos.setFont(new Font("CocogooseProTrial", Font.PLAIN, 18));
        Quitar3.setFont(new Font("Caviar Dreams", Font.PLAIN, 14));
        Detalles3.setFont(new Font("Caviar Dreams", Font.PLAIN, 14));
        jComboBox1.setFont(new Font("Caviar Dreams", Font.PLAIN, 15));
        Todavia.setFont(new Font("CocogooseProTrial", Font.PLAIN, 24));
        Explora.setFont(new Font("Caviar Dreams", Font.PLAIN, 18));

        //Bordes Redondeados ComboBox:
        String[] provincias = {
            "Lugares", "Iglesias", "Museos"
        };

        jComboBox1.setModel(new DefaultComboBoxModel<>(provincias));
        jComboBox1.setSelectedIndex(-1);

        jComboBox1.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index,
                    boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

                if (index == -1 && value == null) {
                    setText("Filtrar por:");
                }

                return this;
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        Favoritos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Guarda = new javax.swing.JLabel();
        Usuario_Favoritos = new javax.swing.JLabel();
        Favoritos1 = new javax.swing.JLabel();
        jPanel2 = new RoundedPanel();
        jLabel2 = new javax.swing.JLabel();
        HotelYanun = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new RoundedPanel();
        jLabel4 = new javax.swing.JLabel();
        Quitar = new javax.swing.JButton();
        jPanel4 = new RoundedPanel();
        Detalles = new javax.swing.JButton();
        jPanel5 = new RoundedPanel();
        jLabel5 = new javax.swing.JLabel();
        IglesiaSan = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new RoundedPanel();
        jLabel7 = new javax.swing.JLabel();
        Quitar1 = new javax.swing.JButton();
        jPanel9 = new RoundedPanel();
        Detalles1 = new javax.swing.JButton();
        jPanel8 = new RoundedPanel();
        jLabel8 = new javax.swing.JLabel();
        IglesiaSanBlas = new javax.swing.JLabel();
        jPanel7 = new RoundedPanel();
        jLabel10 = new javax.swing.JLabel();
        Quitar2 = new javax.swing.JButton();
        jPanel10 = new RoundedPanel();
        Detalles2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel11 = new RoundedPanel();
        jLabel11 = new javax.swing.JLabel();
        IglesiaTodos = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel12 = new RoundedPanel();
        jLabel13 = new javax.swing.JLabel();
        Quitar3 = new javax.swing.JButton();
        jPanel13 = new RoundedPanel();
        Detalles3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jComboBox1 = new Combobox<>(new String[]{
            "Lugares","Museos","Iglesias"});
    jPanel14 = new RoundedPanel();
    jLabel15 = new javax.swing.JLabel();
    Todavia = new javax.swing.JLabel();
    Explora = new javax.swing.JLabel();
    jButton1 = new RoundedButtonAceptarComentario("");

    setPreferredSize(new java.awt.Dimension(1090, 800));
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    content.setBackground(new java.awt.Color(250, 250, 250));
    content.setForeground(new java.awt.Color(250, 250, 250));
    content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    Favoritos.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
    Favoritos.setForeground(new java.awt.Color(0, 0, 0));
    Favoritos.setText("Mis favoritos");
    content.add(Favoritos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/corazon (1) (1).png"))); // NOI18N
    content.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 24, 30, 40));

    Guarda.setForeground(new java.awt.Color(0, 0, 0));
    Guarda.setText("Guarda aquí los lugares que más te insipiran.");
    content.add(Guarda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

    Usuario_Favoritos.setForeground(new java.awt.Color(0, 0, 0));
    Usuario_Favoritos.setText("Usuario > ");
    content.add(Usuario_Favoritos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

    Favoritos1.setForeground(new java.awt.Color(0, 0, 0));
    Favoritos1.setText("Favoritos");
    content.add(Favoritos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

    jPanel2.setForeground(new java.awt.Color(250, 250, 250));
    jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Hotel Yanuncay.jpg"))); // NOI18N
    jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 180));

    HotelYanun.setForeground(new java.awt.Color(0, 0, 0));
    HotelYanun.setText("Hotel Yanuncay");
    jPanel2.add(HotelYanun, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/5 estrellas.png"))); // NOI18N
    jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 170, 40));

    jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/comprobado (1).png"))); // NOI18N
    jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 20));

    Quitar.setText("Quitar");
    Quitar.setBorderPainted(false);
    Quitar.setContentAreaFilled(false);
    Quitar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    Quitar.setFocusPainted(false);
    jPanel3.add(Quitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

    jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 120, 30));

    jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    Detalles.setText("Ver Detalles");
    Detalles.setBorderPainted(false);
    Detalles.setContentAreaFilled(false);
    Detalles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    Detalles.setFocusPainted(false);
    jPanel4.add(Detalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 2, 130, 20));

    jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 120, 30));

    content.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 470, 180));

    jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Iglesia SanSebastián (1).jpg"))); // NOI18N
    jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 180));

    IglesiaSan.setForeground(new java.awt.Color(0, 0, 0));
    IglesiaSan.setText("Iglesia San Sebastián");
    jPanel5.add(IglesiaSan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

    jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/5 estrellas.png"))); // NOI18N
    jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 160, 30));

    jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/comprobado (1).png"))); // NOI18N
    jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 20));

    Quitar1.setText("Quitar");
    Quitar1.setBorderPainted(false);
    Quitar1.setContentAreaFilled(false);
    Quitar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    Quitar1.setFocusPainted(false);
    jPanel6.add(Quitar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

    jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 120, 30));

    jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    Detalles1.setText("Ver Detalles");
    Detalles1.setBorderPainted(false);
    Detalles1.setContentAreaFilled(false);
    Detalles1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    Detalles1.setFocusPainted(false);
    jPanel9.add(Detalles1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, 120, 20));

    jPanel5.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 130, 30));

    content.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 470, 180));

    jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/IglesiaSanBlas (1).jpg"))); // NOI18N
    jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 180));

    IglesiaSanBlas.setText("Iglesia San Blas");
    jPanel8.add(IglesiaSanBlas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

    jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/comprobado (1).png"))); // NOI18N
    jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 20));

    Quitar2.setText("Quitar");
    Quitar2.setBorderPainted(false);
    Quitar2.setContentAreaFilled(false);
    Quitar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    Quitar2.setFocusPainted(false);
    jPanel7.add(Quitar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

    jPanel8.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 120, 30));

    jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    Detalles2.setText("Ver Detalles");
    Detalles2.setBorderPainted(false);
    Detalles2.setContentAreaFilled(false);
    Detalles2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    Detalles2.setFocusPainted(false);
    jPanel10.add(Detalles2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 120, 20));

    jPanel8.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 130, 30));

    jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/5 estrellas.png"))); // NOI18N
    jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 160, 30));

    content.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 470, 180));

    jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/IglesiaTodosSantos (1).jpg"))); // NOI18N
    jPanel11.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 240, 180));

    IglesiaTodos.setForeground(new java.awt.Color(0, 0, 0));
    IglesiaTodos.setText("Iglesia Todos Santos");
    jPanel11.add(IglesiaTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

    jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/5 estrellas.png"))); // NOI18N
    jPanel11.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 160, 30));

    jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/comprobado (1).png"))); // NOI18N
    jPanel12.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 20));

    Quitar3.setText("Quitar");
    Quitar3.setBorderPainted(false);
    Quitar3.setContentAreaFilled(false);
    Quitar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    Quitar3.setFocusPainted(false);
    jPanel12.add(Quitar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

    jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 120, 30));

    jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    Detalles3.setText("Ver Detalles");
    Detalles3.setBorderPainted(false);
    Detalles3.setContentAreaFilled(false);
    Detalles3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    Detalles3.setFocusPainted(false);
    jPanel13.add(Detalles3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 120, 20));

    jPanel11.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 130, 30));

    content.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 470, 180));

    jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Menu 2.png"))); // NOI18N
    content.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 14, 60, 60));

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ordenar por:" }));
    jComboBox1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBox1ActionPerformed(evt);
        }
    });
    content.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 24, 180, 40));

    jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Mapeo 3.png"))); // NOI18N
    jPanel14.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 110, 90));

    Todavia.setForeground(new java.awt.Color(0, 0, 0));
    Todavia.setText("¿Todavía no tienes favoritos?");
    jPanel14.add(Todavia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

    Explora.setForeground(new java.awt.Color(0, 0, 0));
    Explora.setText("Explora y guarda tus lugares favoritos.");
    jPanel14.add(Explora, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

    jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jButton1.setText("Buscar");
    jButton1.setBorderPainted(false);
    jButton1.setContentAreaFilled(false);
    jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButton1.setFocusPainted(false);
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });
    jPanel14.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 102, 140, 30));

    content.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 1000, 160));

    getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 800));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Ventanas_MostrarMás MiLugar = new Ventanas_MostrarMás();
        MiLugar.setSize(1140, 830);

        content.removeAll();
        content.add(MiLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 830));
        content.revalidate();
        content.repaint();


    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Detalles;
    private javax.swing.JButton Detalles1;
    private javax.swing.JButton Detalles2;
    private javax.swing.JButton Detalles3;
    private javax.swing.JLabel Explora;
    private javax.swing.JLabel Favoritos;
    private javax.swing.JLabel Favoritos1;
    private javax.swing.JLabel Guarda;
    private javax.swing.JLabel HotelYanun;
    private javax.swing.JLabel IglesiaSan;
    private javax.swing.JLabel IglesiaSanBlas;
    private javax.swing.JLabel IglesiaTodos;
    private javax.swing.JButton Quitar;
    private javax.swing.JButton Quitar1;
    private javax.swing.JButton Quitar2;
    private javax.swing.JButton Quitar3;
    private javax.swing.JLabel Todavia;
    private javax.swing.JLabel Usuario_Favoritos;
    private javax.swing.JPanel content;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
