/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Vista.*;
import Controlador.ControladorIglesia;
import Controlador.ControladorMuseo;
import Controlador.ControladorParque;
import Design.Panel.WrapLayout;
import Modelo.Iglesia;
import Modelo.Iglesia;
import Modelo.IglesiaVista;
import Modelo.IglesiaVista;
import Modelo.Museo;
import Modelo.MuseoVista;
import Modelo.Parque;
import Modelo.ParqueVista;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;

/**
 *
 * @author USER
 */
public class Ventana_TarjetasParque extends javax.swing.JFrame {

    private List<Parque> museosGuardados;
    private ControladorParque ctrl = new ControladorParque();

    /**
     * Creates new form Ventana_TarjetasIglesia
     */
    public Ventana_TarjetasParque() {
        initComponents();

        
        //Cargar el Scroll Panel para las tarjetas de las iglesias.
        jPanelContenedorMuseos.setLayout(new WrapLayout(FlowLayout.CENTER, 15, 15));
        jPanelContenedorMuseos.setBackground(Color.WHITE);

        JScrollPane scroll = new JScrollPane(jPanelContenedorMuseos);
        scroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scroll.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);

        jPanelCentro.setLayout(new BorderLayout());
        jPanelCentro.add(scroll, BorderLayout.CENTER);

        //Fuentes:
        Registro.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 30));

        //Extender la ventana al máximo: 
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        // Para pantalla completa:
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        jPanelContenedorMuseos.setBorder(BorderFactory.createEmptyBorder(10, 10, 70, 10));

        cargarParques();
    }

    
    //Cargar todas las iglesias existentes:
    public void cargarParques() {
        try {
            List<ParqueVista> lista = ctrl.obtenerMuseosVista();

            for (ParqueVista iv : lista) {
                agregarTarjeta(iv.getNombre(),iv.getEntidad_gestora(),iv.getSuperficie(), iv.getImagenPrincipal());
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar parques: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    //Agregar las tarjetas:
    public void agregarTarjeta(String nombre, String entidad_gestora, float superficie, byte[] imagen) {
        PanelCardParque tarjeta = new PanelCardParque(nombre, entidad_gestora, superficie, imagen);
        tarjeta.setAlignmentX(Component.LEFT_ALIGNMENT);
        jPanelContenedorMuseos.add(tarjeta);
        jPanelContenedorMuseos.revalidate();
        jPanelContenedorMuseos.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Registro = new javax.swing.JLabel();
        jPanelCentro = new javax.swing.JPanel();
        jPanelContenedorMuseos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(149, 125, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Registro.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Registro.setForeground(new java.awt.Color(255, 255, 255));
        Registro.setText("Mis Museos");
        jPanel1.add(Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 340, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 90));

        javax.swing.GroupLayout jPanelContenedorMuseosLayout = new javax.swing.GroupLayout(jPanelContenedorMuseos);
        jPanelContenedorMuseos.setLayout(jPanelContenedorMuseosLayout);
        jPanelContenedorMuseosLayout.setHorizontalGroup(
            jPanelContenedorMuseosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
        );
        jPanelContenedorMuseosLayout.setVerticalGroup(
            jPanelContenedorMuseosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelCentroLayout = new javax.swing.GroupLayout(jPanelCentro);
        jPanelCentro.setLayout(jPanelCentroLayout);
        jPanelCentroLayout.setHorizontalGroup(
            jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentroLayout.createSequentialGroup()
                .addComponent(jPanelContenedorMuseos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelCentroLayout.setVerticalGroup(
            jPanelCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentroLayout.createSequentialGroup()
                .addComponent(jPanelContenedorMuseos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1370, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_TarjetasParque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_TarjetasParque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_TarjetasParque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_TarjetasParque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_TarjetasParque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Registro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCentro;
    private javax.swing.JPanel jPanelContenedorMuseos;
    // End of variables declaration//GEN-END:variables

}
