/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.event.MouseInputAdapter;
import javax.swing.event.MouseInputListener;
import org.jxmapviewer.JXMapViewer;
import org.jxmapviewer.OSMTileFactoryInfo;
import org.jxmapviewer.VirtualEarthTileFactoryInfo;
import org.jxmapviewer.input.PanMouseInputListener;
import org.jxmapviewer.input.ZoomMouseWheelListenerCenter;
import org.jxmapviewer.viewer.DefaultTileFactory;
import org.jxmapviewer.viewer.GeoPosition;
import org.jxmapviewer.viewer.TileFactoryInfo;

/**
 *
 * @author Usuario_2
 */
public class Vista_Registro_Iglesias extends javax.swing.JFrame {

    /**
     * Creates new form Vista_Registro_Iglesias
     */
    public Vista_Registro_Iglesias() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBase = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHora_aper = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHoracierre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jxMap = new org.jxmapviewer.JXMapViewer();
        comboMapTypes = new javax.swing.JComboBox<>();
        jBtnGuardar = new javax.swing.JButton();
        jBtnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelBase.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre:");
        PanelBase.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        PanelBase.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 140, -1));

        jLabel2.setText("Hora de apertura:");
        PanelBase.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        PanelBase.add(txtHora_aper, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 120, -1));

        jLabel3.setText("Hora de cierre:");
        PanelBase.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        PanelBase.add(txtHoracierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 120, -1));

        jLabel4.setText("Direccion:");
        PanelBase.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));
        PanelBase.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 140, -1));

        jxMap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 6, 6)));

        comboMapTypes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Open Stree", "Virtual Earth", "Hybrid", "Satellite" }));
        comboMapTypes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMapTypesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jxMapLayout = new javax.swing.GroupLayout(jxMap);
        jxMap.setLayout(jxMapLayout);
        jxMapLayout.setHorizontalGroup(
            jxMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jxMapLayout.createSequentialGroup()
                .addGap(0, 270, Short.MAX_VALUE)
                .addComponent(comboMapTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jxMapLayout.setVerticalGroup(
            jxMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jxMapLayout.createSequentialGroup()
                .addComponent(comboMapTypes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 226, Short.MAX_VALUE))
        );

        PanelBase.add(jxMap, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 370, 250));

        jBtnGuardar.setText("Guardar");
        PanelBase.add(jBtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        jBtnModificar.setText("Modificar");
        PanelBase.add(jBtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboMapTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMapTypesActionPerformed

        TileFactoryInfo info;
        int  index = comboMapTypes.getSelectedIndex();
        if(index == 0){
           info =new OSMTileFactoryInfo();
        }else if(index == 1){
            info =new VirtualEarthTileFactoryInfo(VirtualEarthTileFactoryInfo.MAP);
        }else if(index ==2){
             info =new VirtualEarthTileFactoryInfo(VirtualEarthTileFactoryInfo.HYBRID);
        }else {
            info =new VirtualEarthTileFactoryInfo(VirtualEarthTileFactoryInfo.SATELLITE);
        }
         DefaultTileFactory tileFactory =new DefaultTileFactory(info);
         jxMap.setTileFactory(tileFactory);
    }//GEN-LAST:event_comboMapTypesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Registro_Iglesias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Registro_Iglesias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Registro_Iglesias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Registro_Iglesias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Registro_Iglesias().setVisible(true);
            }
        });
    }
    
    private void init(){
        TileFactoryInfo info =new OSMTileFactoryInfo();
        DefaultTileFactory tileFactory =new DefaultTileFactory(info);
        jxMap.setTileFactory(tileFactory);
        GeoPosition geo =new GeoPosition(-2.8985774,-79.013287);
        jxMap.setAddressLocation(geo);
        jxMap.setZoom(3);
        MouseInputListener mouse =new PanMouseInputListener(jxMap);
        jxMap.addMouseListener(mouse);
        jxMap.addMouseMotionListener(mouse);
        jxMap.addMouseWheelListener(new ZoomMouseWheelListenerCenter(jxMap));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBase;
    private javax.swing.JComboBox<String> comboMapTypes;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JButton jBtnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private org.jxmapviewer.JXMapViewer jxMap;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtHora_aper;
    private javax.swing.JTextField txtHoracierre;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
