/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista.PanelIglesias;
import Design.RoundedPanel;
import Design.RoundedPanelCarrusel;
/**
 *
 * @author USER
 */
public class ElSagrario extends javax.swing.JPanel {

    /**
     * Creates new form ElSagrario
     */
    public ElSagrario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanelCarrusel1 = new Design.RoundedPanelCarrusel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout roundedPanelCarrusel1Layout = new javax.swing.GroupLayout(roundedPanelCarrusel1);
        roundedPanelCarrusel1.setLayout(roundedPanelCarrusel1Layout);
        roundedPanelCarrusel1Layout.setHorizontalGroup(
            roundedPanelCarrusel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        roundedPanelCarrusel1Layout.setVerticalGroup(
            roundedPanelCarrusel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        add(roundedPanelCarrusel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 550, 370));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Design.RoundedPanelCarrusel roundedPanelCarrusel1;
    // End of variables declaration//GEN-END:variables
}
